"""Bake the fitted p(theta) ensemble into the Rust seed sampler.

Reads `out/p_theta/weights.parquet` (the density-ratio-weighted design points,
in real units) and emits `golf-terrain/src/sampler/ptheta.rs`: the design points
in UNIT space, a cumulative-weight CDF for deterministic weighted resampling, and
the per-knob (lo, hi, log, int) spec so the Rust side can decode unit -> theta
exactly like `param_schema._from_unit`.

This is the "full re-fit" bridge: the shipped sampler resamples this ensemble
(with small unit-space jitter) instead of the old analytic relief-mixture draws.
Re-run after every campaign:  python3 -m calibration.export_sampler
"""

from __future__ import annotations

import os

import numpy as np
import pandas as pd

from . import param_schema as ps

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "out"))
REPO = os.path.normpath(os.path.join(HERE, "..", "..", ".."))
REAL_PATH = os.path.join(REPO, "tools", "metrics", "out", "features_scalar.parquet")
DEST = os.path.normpath(
    os.path.join(HERE, "..", "..", "..", "golf-terrain", "src", "sampler", "ptheta.rs")
)


def relief_axis_correction(wdf, n_bins=12, clip=(0.2, 5.0), strength=1.0):
    """1-D reweight so the WEIGHTED relief distribution of the ensemble matches
    the real atlas relief distribution (density-ratio matching concentrates
    weight at the reachability-hard corners, starving mid-relief mass — the
    most user-visible axis). Per-quantile-bin ratio real_share/fit_share,
    tempered by ``strength`` (ratio^strength: 1 = exact-match, 0 = off — full
    strength costs ~+0.5 energy on the other 40 axes because starved bins hold
    design points the classifier down-weighted for a reason), clipped,
    renormalized. Returns (new_weights, report_str)."""
    fwd = pd.read_parquet(os.path.join(OUT, "samples", "forward.parquet"))
    ok = fwd[fwd.status == "ok"]
    relief = ok.groupby("theta_id")["relief_p95_p5"].mean()
    r = wdf["theta_id"].map(relief).to_numpy(float)
    w = wdf["weight"].to_numpy(float).copy()
    real = pd.read_parquet(REAL_PATH)
    rr = real[real.clip_variant == "course_extent"]["relief_p95_p5"].dropna().to_numpy(float)
    # bins from real quantiles (equal real mass per bin), open-ended edges
    edges = np.quantile(rr, np.linspace(0, 1, n_bins + 1))
    edges[0], edges[-1] = -np.inf, np.inf
    idx = np.clip(np.searchsorted(edges, r, side="right") - 1, 0, n_bins - 1)
    fit_share = np.array([w[idx == b].sum() for b in range(n_bins)])
    fit_share = fit_share / fit_share.sum()
    real_share = 1.0 / n_bins
    ratio = real_share / np.maximum(fit_share, 1e-9)
    ratio = np.clip(ratio ** float(strength), clip[0], clip[1])
    w2 = w * ratio[idx]
    w2 = w2 / w2.sum()

    def q(wv, p):
        i = np.argsort(r)
        cw = np.cumsum(wv[i])
        return r[i][np.searchsorted(cw, p)]

    rep = (f"relief-axis reweight: median {q(w/w.sum(),.5):.1f}->{q(w2,.5):.1f} "
           f"(real {np.median(rr):.1f}), p95 {q(w/w.sum(),.95):.1f}->{q(w2,.95):.1f} "
           f"(real {np.quantile(rr,.95):.1f}), "
           f"share>=65m {w[r>=65].sum()/w.sum()*100:.1f}%->{w2[r>=65].sum()*100:.1f}% "
           f"(real {(rr>=65).mean()*100:.1f}%)")
    return w2, rep


def _fmt_row(u):
    return "    [" + ", ".join(f"{x:.6f}" for x in u) + "],"


def build(weights=None, dest=DEST, match_relief=True):
    if weights is None:
        weights = os.path.join(OUT, "p_theta", "weights.parquet")
    wdf = pd.read_parquet(weights)
    names = ps.NAMES
    n, d = len(wdf), len(names)

    # design points -> unit space (exactly the space the jitter lives in)
    U = np.empty((n, d), float)
    for j, nm in enumerate(names):
        U[:, j] = [ps._to_unit(nm, v) for v in wdf[nm].to_numpy(float)]
    U = np.clip(U, 0.0, 1.0)

    # normalized weights (+ optional relief-axis correction), cumulative CDF.
    # strength 0.5 / clip (0.4, 2.5): the measured trade (2026-07-12) was
    # median 11.0->16.9 (real 19.8) for +0.26 energy; full strength hits the
    # median exactly but costs +0.53 by boosting classifier-rejected designs.
    relief_note = "relief-axis reweight: off"
    if match_relief:
        w, relief_note = relief_axis_correction(wdf, strength=0.5, clip=(0.4, 2.5))
        print(f"export_sampler: {relief_note}")
    else:
        w = wdf["weight"].to_numpy(float)
    w = w / w.sum()
    cdf = np.cumsum(w)
    cdf[-1] = 1.0

    lo = [p[2] for p in ps.PARAMS]
    hi = [p[3] for p in ps.PARAMS]
    is_log = [p[4] == "log" for p in ps.PARAMS]
    is_int = [bool(p[5]) for p in ps.PARAMS]

    L = []
    L.append("//! GENERATED by `python3 -m calibration.export_sampler` — do not edit.")
    L.append("//! The fitted p(theta) ensemble (density-ratio weighted design points)")
    L.append("//! baked for the seed sampler: unit-space design + weight CDF + knob spec.")
    L.append(f"//! {relief_note}")
    L.append("")
    L.append(f"/// Number of theta knobs (order matches `PSPEC` / `param_schema.NAMES`).")
    L.append(f"pub const NP: usize = {d};")
    L.append(f"/// Number of design points in the fitted ensemble.")
    L.append(f"pub const NPTS: usize = {n};")
    L.append("")
    L.append("/// Per-knob decode spec: (lo, hi, is_log, is_int). Mirrors")
    L.append("/// `param_schema._from_unit`: log knobs use `lo*(hi/lo)^u`, linear use")
    L.append("/// `lo + u*(hi-lo)`, int knobs round.")
    order = ", ".join(names)
    L.append(f"/// Order: {order}")
    L.append(f"pub const PSPEC: [(f64, f64, bool, bool); NP] = [")
    for j in range(d):
        L.append(
            f"    ({lo[j]:.6}, {hi[j]:.6}, {str(is_log[j]).lower()}, {str(is_int[j]).lower()}),"
            f"  // {names[j]}"
        )
    L.append("];")
    L.append("")
    L.append("/// Design points in unit space `[0,1]^NP`, one row per ensemble member.")
    L.append(f"pub static PTHETA_U: [[f64; NP]; NPTS] = [")
    for i in range(n):
        L.append(_fmt_row(U[i]))
    L.append("];")
    L.append("")
    L.append("/// Cumulative normalized p(theta) weights (ascending, last = 1.0).")
    L.append("/// Weighted resampling: draw uniform `x`, take the first `i` with `x <= CDF[i]`.")
    L.append(f"pub static PTHETA_CDF: [f64; NPTS] = [")
    for i in range(0, n, 6):
        chunk = ", ".join(f"{c:.9f}" for c in cdf[i : i + 6])
        L.append(f"    {chunk},")
    L.append("];")
    L.append("")

    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w") as f:
        f.write("\n".join(L))

    ess = float(1.0 / np.sum(w ** 2))
    print(f"export_sampler: wrote {dest}")
    print(f"  {n} design points x {d} knobs; ESS {ess:.0f} ({100*ess/n:.0f}% of design)")
    return dest


if __name__ == "__main__":
    build()
