//! Flow routing with Barnes flat resolution — the D2 kernel, shared by S2's
//! verification and S4's hydrology.
//!
//! This is a line-faithful port of `tools/macro_campaign/macro_campaign/flow.py`
//! (see its docstring for why flat-blind D8 is disqualified: tie-breaking by
//! direction order drew dead-straight axis-aligned "channels" across every
//! lake and graded flat in the QA corpus). The port must stay behaviorally
//! identical — `tests/flow_parity.rs` pins it to fixtures generated by the
//! Python original on a real-tile crop, so any divergence is a test failure,
//! not a silent drift.
//!
//! Determinism: no hash maps, no float ambiguity beyond IEEE ops in the same
//! order as the original, ties broken by explicit insertion order (fill) and
//! by fixed direction order (receivers, flat BFS).
//!
//! Inputs are assumed finite everywhere: generated surfaces have no nodata.
//! (The Python original nearest-fills nodata first; real-tile use stays on
//! the Python side.)

use std::cmp::Reverse;
use std::collections::BinaryHeap;

use crate::grid::Grid;

/// D8 neighbourhood, `(dy, dx)`, in the Python original's order. The order
/// is semantic: receiver ties and flat-BFS adoption both resolve to the
/// FIRST direction in this list.
pub const D8: [(i64, i64); 8] = [
    (-1, -1),
    (-1, 0),
    (-1, 1),
    (0, -1),
    (0, 1),
    (1, -1),
    (1, 0),
    (1, 1),
];

const SQRT2: f64 = 1.4142135623730951;

/// Total-ordered f64 for the priority queue (all inputs finite).
#[derive(PartialEq)]
struct Ord64(f64);
impl Eq for Ord64 {}
impl PartialOrd for Ord64 {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}
impl Ord for Ord64 {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.0.total_cmp(&other.0)
    }
}

/// Priority-flood depression filling (Barnes et al.), epsilon-graded so
/// every filled flat still routes. Border cells are open outlets.
///
/// Matches `metrics.core.fill_depressions`: min-heap keyed on
/// `(z, insertion_order)`, borders seeded left/right column per row then
/// top/bottom row per column, `eps = 1e-4 * cell`.
pub fn fill_depressions(z: &Grid<f64>) -> Grid<f64> {
    let (ny, nx) = (z.spec.ny as usize, z.spec.nx as usize);
    let eps = 1e-4 * z.spec.cell_size;
    let mut filled = z.clone();
    let mut closed = vec![false; ny * nx];
    // (z, order, lin) — order makes ties FIFO like Python's heapq tuples.
    let mut pq: BinaryHeap<Reverse<(Ord64, u64, usize)>> = BinaryHeap::new();
    let mut order: u64 = 0;
    let mut push = |pq: &mut BinaryHeap<_>, closed: &mut Vec<bool>, lin: usize, zv: f64| {
        pq.push(Reverse((Ord64(zv), order, lin)));
        order += 1;
        closed[lin] = true;
    };
    for y in 0..ny {
        for x in [0, nx - 1] {
            let lin = y * nx + x;
            if !closed[lin] {
                push(&mut pq, &mut closed, lin, z.data[lin]);
            }
        }
    }
    for x in 0..nx {
        for y in [0, ny - 1] {
            let lin = y * nx + x;
            if !closed[lin] {
                push(&mut pq, &mut closed, lin, z.data[lin]);
            }
        }
    }
    while let Some(Reverse((Ord64(zc), _, lin))) = pq.pop() {
        filled.data[lin] = zc;
        let (y, x) = ((lin / nx) as i64, (lin % nx) as i64);
        for (dy, dx) in D8 {
            let (ny2, nx2) = (y + dy, x + dx);
            if ny2 < 0 || nx2 < 0 || ny2 >= ny as i64 || nx2 >= nx as i64 {
                continue;
            }
            let nlin = ny2 as usize * nx + nx2 as usize;
            if !closed[nlin] {
                let zn = z.data[nlin].max(zc + eps);
                pq.push(Reverse((Ord64(zn), order, nlin)));
                order += 1;
                closed[nlin] = true;
            }
        }
    }
    filled
}

/// Steepest-descent receivers on the filled surface, flats resolved by a
/// wave-synchronous BFS grown inward from each flat's spill cells.
///
/// Returns `(rec, slope)`: `rec[i]` is the linear receiver index or `-1`
/// (outlet/undrained); `slope[i]` the gradient toward it on `zfill`
/// (0 across flats).
pub fn receivers(zfill: &Grid<f64>, cell: f64) -> (Vec<i64>, Vec<f64>) {
    let (ny, nx) = (zfill.spec.ny as usize, zfill.spec.nx as usize);
    let n = ny * nx;
    let z = &zfill.data;
    let mut rec = vec![-1i64; n];
    let mut slope = vec![0.0f64; n];

    let at = |y: i64, x: i64| -> Option<usize> {
        if y < 0 || x < 0 || y >= ny as i64 || x >= nx as i64 {
            None
        } else {
            Some(y as usize * nx + x as usize)
        }
    };

    for lin in 0..n {
        let (y, x) = ((lin / nx) as i64, (lin % nx) as i64);
        let mut best = 0.0f64;
        for (dy, dx) in D8 {
            let Some(nlin) = at(y + dy, x + dx) else { continue };
            let dist = cell * if dy != 0 && dx != 0 { SQRT2 } else { 1.0 };
            let s = (z[lin] - z[nlin]) / dist;
            if s > best {
                best = s;
                rec[lin] = nlin as i64;
            }
        }
        slope[lin] = best;
    }

    // Flat resolution: wave-synchronous BFS. Candidates only adopt receivers
    // assigned in PRIOR waves (Python's `assigned` snapshot), and a flat cell
    // takes the first D8 direction whose neighbour qualifies — a candidate
    // receiver must sit at the same elevation or lower, else 2-cycles form.
    let mut assigned: Vec<bool> = rec.iter().map(|&r| r >= 0).collect();
    if assigned.iter().any(|a| !a) {
        loop {
            let mut newly: Vec<usize> = Vec::new();
            for lin in 0..n {
                if assigned[lin] {
                    continue;
                }
                let (y, x) = ((lin / nx) as i64, (lin % nx) as i64);
                for (dy, dx) in D8 {
                    let Some(nlin) = at(y + dy, x + dx) else { continue };
                    if assigned[nlin] && z[nlin] <= z[lin] {
                        rec[lin] = nlin as i64;
                        newly.push(lin);
                        break;
                    }
                }
            }
            if newly.is_empty() {
                break;
            }
            for lin in newly {
                assigned[lin] = true;
            }
        }
    }
    (rec, slope)
}

/// Number of cells draining through each cell (including itself), by
/// in-degree topological order — O(n), no recursion.
pub fn accumulate(rec: &[i64]) -> Vec<i64> {
    let n = rec.len();
    let mut acc = vec![1i64; n];
    let mut indeg = vec![0i64; n];
    for &r in rec {
        if r >= 0 {
            indeg[r as usize] += 1;
        }
    }
    let mut stack: Vec<usize> = (0..n).filter(|&i| indeg[i] == 0).collect();
    while let Some(i) = stack.pop() {
        let r = rec[i];
        if r < 0 {
            continue;
        }
        let r = r as usize;
        acc[r] += acc[i];
        indeg[r] -= 1;
        if indeg[r] == 0 {
            stack.push(r);
        }
    }
    acc
}

/// The routed flow field: fill → receivers → accumulate in one call.
pub struct FlowField {
    pub filled: Grid<f64>,
    /// Linear receiver index per cell; -1 = outlet.
    pub rec: Vec<i64>,
    /// Gradient toward the receiver on the filled surface (0 across flats).
    pub slope: Vec<f64>,
    /// Cells draining through each cell, including itself.
    pub acc: Vec<i64>,
}

pub fn route(z: &Grid<f64>) -> FlowField {
    let filled = fill_depressions(z);
    let (rec, slope) = receivers(&filled, z.spec.cell_size);
    let acc = accumulate(&rec);
    FlowField { filled, rec, slope, acc }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::grid::GridSpec;
    use crate::math::Vec2;

    fn grid(ny: usize, nx: usize, f: impl Fn(usize, usize) -> f64) -> Grid<f64> {
        let spec = GridSpec::new(Vec2::new(0.0, 0.0), 1.0, nx as u32, ny as u32);
        let mut data = Vec::with_capacity(ny * nx);
        for y in 0..ny {
            for x in 0..nx {
                data.push(f(y, x));
            }
        }
        Grid { spec, data }
    }

    #[test]
    fn tilted_plane_drains_everywhere() {
        let g = grid(16, 16, |y, x| (y + x) as f64 * 0.1);
        let ff = route(&g);
        // corner (0,0) is the low point: it is an outlet and collects all.
        assert_eq!(ff.rec[0], -1);
        let total: i64 = ff
            .rec
            .iter()
            .zip(&ff.acc)
            .filter(|(r, _)| **r < 0)
            .map(|(_, a)| a)
            .sum();
        assert_eq!(total, 16 * 16, "every cell reaches an outlet");
    }

    #[test]
    fn bowl_fills_and_drains_to_rim_low() {
        // A closed bowl in a plane tilted toward x=0. Filling must let the
        // interior escape through the west, not strand it.
        let g = grid(32, 32, |y, x| {
            let base = x as f64 * 0.05;
            let (dy, dx) = (y as f64 - 16.0, x as f64 - 16.0);
            let r = (dy * dy + dx * dx).sqrt();
            base + if r < 8.0 { r - 8.0 } else { 0.0 }
        });
        let ff = route(&g);
        let total: i64 = ff
            .rec
            .iter()
            .zip(&ff.acc)
            .filter(|(r, _)| **r < 0)
            .map(|(_, a)| a)
            .sum();
        assert_eq!(total, 32 * 32);
        // filled bowl floor is a graded flat: no cell below the fill level
        let center = 16 * 32 + 16;
        assert!(ff.filled.data[center] > g.data[center]);
    }

    #[test]
    fn no_straight_channels_across_flats() {
        // The disqualifying artifact: a filled lake crossed by a dead-straight
        // axis-aligned channel. Build a valley draining through a circular
        // lake whose outlet is OFF the inlet's row; the max-accumulation path
        // through the lake must bend toward the true spill, i.e. the drained
        // path's rows must vary inside the flat.
        let ny = 48;
        let nx = 48;
        let g = grid(ny, nx, |y, x| {
            let vx = 10.0 + x as f64 * 0.1; // gentle eastward fall
            let (dy, dx) = (y as f64 - 20.0, x as f64 - 24.0);
            let r = (dy * dy + dx * dx).sqrt();
            let lake = if r < 9.0 { -(3.0) } else { 0.0 };
            // valley walls funnel flow along row 20 into the lake from west;
            // the spill sits southeast of the lake at row 30.
            let wall = 0.4 * (y as f64 - 30.0).abs().min((y as f64 - 20.0).abs());
            vx + lake + wall
        });
        let ff = route(&g);
        // channel = top-decile accumulation cells inside the (filled) flat
        let flat: Vec<usize> = (0..ny * nx)
            .filter(|&i| ff.filled.data[i] > g.data[i] + 0.01)
            .collect();
        assert!(flat.len() > 50, "the lake filled ({} cells)", flat.len());
        let mut accs: Vec<i64> = flat.iter().map(|&i| ff.acc[i]).collect();
        accs.sort_unstable();
        let thresh = accs[accs.len() * 9 / 10];
        let rows: std::collections::BTreeSet<usize> = flat
            .iter()
            .filter(|&&i| ff.acc[i] >= thresh)
            .map(|&i| i / nx)
            .collect();
        assert!(
            rows.len() >= 3,
            "high-accumulation path is axis-aligned across the flat (rows: {rows:?})"
        );
    }

    #[test]
    fn accumulation_conserves_mass() {
        let g = grid(20, 20, |y, x| {
            ((y as f64 * 0.7).sin() + (x as f64 * 1.3).cos()) * 2.0 + y as f64 * 0.05
        });
        let ff = route(&g);
        let outlet_sum: i64 = ff
            .rec
            .iter()
            .zip(&ff.acc)
            .filter(|(r, _)| **r < 0)
            .map(|(_, a)| a)
            .sum();
        assert_eq!(outlet_sum, 400, "no basin silently dropped (2-cycle guard)");
    }
}
