//! GENERATED by `cargo run -p xtask --release -- calibrate` — do not edit.
//! Measured on the 128×128 2 km world, seeds 0..10, using the sampler's own
//! octave/warp rules.

/// Base-period axis of the tables, meters.
pub const CAL_PERIODS: [f64; 7] = [250.0, 500.0, 800.0, 1200.0, 1600.0, 2000.0, 2400.0];
/// Gain axis of the tables.
pub const CAL_GAINS: [f64; 5] = [0.50, 0.57, 0.64, 0.71, 0.78];

/// p2–p98 relief of a unit-amplitude field over the 2 km window.
pub const K_RELIEF: [[f64; 5]; 7] = [
    [0.8010, 0.7757, 0.7556, 0.7403, 0.7297],
    [0.7351, 0.7003, 0.6716, 0.6494, 0.6339],
    [0.6592, 0.6181, 0.5847, 0.5596, 0.5436],
    [0.6540, 0.6134, 0.5780, 0.5471, 0.5256],
    [0.5922, 0.5662, 0.5418, 0.5209, 0.5046],
    [0.5279, 0.5097, 0.4954, 0.4848, 0.4778],
    [0.4924, 0.4778, 0.4657, 0.4551, 0.4470],
];

/// Redistribution strength axis (the e ≥ 1 branch; the p < 1 side mirrors it
/// exactly because the raw field is symmetric).
pub const CAL_REDIST: [f64; 6] = [1.00, 1.60, 2.50, 4.00, 6.50, 10.00];
/// Height skewness produced by each strength.
pub const SKEW_REDIST: [f64; 6] = [0.0279, 0.2351, 0.5379, 1.0316, 1.8498, 3.0017];
/// Relief multiplier of each strength vs e=1.
pub const K_REDIST: [f64; 6] = [1.0000, 1.0322, 0.8551, 0.5031, 0.1757, 0.0382];

/// Erosion-intensity axis of the pipeline relief table.
pub const CAL_ERODE_T: [f64; 6] = [0.5, 1.0, 2.0, 3.0, 4.5, 6.0];
/// Base-period axis of the pipeline relief table (measured at each period's
/// mode-typical gain; deposition barely moves retention and has no axis).
pub const CAL_ERODE_P: [f64; 3] = [800.0, 1400.0, 2000.0];
/// Pipeline relief multiplier vs the un-eroded field.
pub const K_ERODE: [[f64; 3]; 6] = [
    [0.9491, 0.9783, 0.9874],
    [0.9270, 0.9642, 0.9760],
    [0.8758, 0.9325, 0.9495],
    [0.8345, 0.9059, 0.9283],
    [0.7940, 0.8785, 0.9058],
    [0.7706, 0.8630, 0.8929],
];

/// In-window correlation half-length as a fraction of base period. Measured
/// for reference; the p(θ) sampler draws base_period directly, so it is unread.
#[allow(dead_code)]
pub const C_RHALF: [[f64; 5]; 7] = [
    [0.3042, 0.2855, 0.2657, 0.2440, 0.2220],
    [0.2995, 0.2759, 0.2493, 0.2205, 0.1914],
    [0.2738, 0.2498, 0.2229, 0.1920, 0.1581],
    [0.2628, 0.2404, 0.2139, 0.1832, 0.1499],
    [0.2242, 0.2046, 0.1849, 0.1622, 0.1351],
    [0.2091, 0.1921, 0.1729, 0.1497, 0.1242],
    [0.1876, 0.1722, 0.1543, 0.1333, 0.1094],
];
