"""Finalize: F2 finalists -> the committed tile index
(tools/dtm_atlas/tiles_us.txt + tiles_us.json). Checks 1 m availability per
finalist (the one per-tile index query of the campaign) and back-fills from
the next-ranked same-region candidates when a finalist lacks 1 m lidar."""

from __future__ import annotations

import json
import os

import numpy as np
import pandas as pd

from . import TILE_SCOUT_VERSION, sconfig


def _avail_1m(row, sess) -> bool:
    """Does real 1 m lidar exist here? The 3DEPElevationIndex service is
    unreliable (documented Stage-0 outage; observed returning 'none' for
    known-1m course bboxes), so the EMPIRICAL test decides: fetch a tiny
    center patch at 1 m and require sub-2 m texture (the same
    texture_frac >= 0.7 rule the course store uses). Index 'best==1m' is
    accepted as a fast positive when the service does answer."""
    import json
    from dtm_atlas import dep3
    cache = sconfig.out_path("cache", "avail", f"{row.key}.json")
    if os.path.exists(cache):
        with open(cache) as f:
            return bool(json.load(f)["ok"])
    lat, lon = float(row.lat), float(row.lon)
    dlat = 1500.0 / 111320.0
    dlon = 1500.0 / (111320.0 * max(0.2, np.cos(np.radians(lat))))
    ok = False
    try:
        av = dep3.query_availability((lat - dlat, lon - dlon,
                                      lat + dlat, lon + dlon), sess)
        ok = av.get("best") == "1m"
    except Exception:
        ok = False
    how = "index"
    if not ok:
        cx = float(row.x0) + 1500.0
        cy = float(row.y0) + 1500.0
        patch = dep3.export_dem((cx - 100, cy - 100, cx + 100, cy + 100),
                                int(row.epsg), 1.0, sess)
        ok = bool(dep3.texture_frac(patch) >= 0.7)
        how = "texture"
    with open(cache, "w") as f:
        json.dump({"ok": ok, "how": how}, f)
    return ok


def finalize(cfg: dict, only_region: str = "", limit: int = 0,
             check_avail: bool = True) -> int:
    import requests
    df = pd.read_parquet(sconfig.out_path("f2_scores.parquet"))
    if only_region:
        regions = [r.strip() for r in only_region.split(",") if r.strip()]
        df = df[df["region"].isin(regions)]
    sess = requests.Session()
    chosen: list[pd.Series] = []
    avail_cache: dict[str, bool] = {}

    for rname, sub in sorted(df.groupby("region")):
        pool = sub.sort_values(["f2_dist", "key"])
        # pilot mode (--limit): draw from the whole scored pool; the global
        # cap below still applies
        want = len(pool) if limit > 0 else int(pool["f2_keep"].sum())
        got = 0
        for row in pool.itertuples():
            if got >= want:
                break
            if check_avail:
                ok = avail_cache.get(row.key)
                if ok is None:
                    ok = _avail_1m(row, sess)
                    avail_cache[row.key] = ok
                if not ok:
                    print(f"  {row.key}: no 1 m signal — replaced")
                    continue
            chosen.append(row)
            got += 1

    rows = sorted(chosen, key=lambda r: (r.f2_dist, r.key))
    if limit > 0:
        rows = rows[:limit]

    # merge with any existing manifest (pilot adds regions incrementally)
    from dtm_atlas import config as atlas_config
    man_p = atlas_config.TILES_MANIFEST
    txt_p = atlas_config.TILES_US
    man = {}
    if os.path.exists(man_p):
        with open(man_p) as f:
            man = json.load(f)
    if only_region:
        keep_regions = set(r.strip() for r in only_region.split(","))
        man = {k: v for k, v in man.items()
               if v.get("region") not in keep_regions}
    else:
        man = {}
    for r in rows:
        man[r.key] = {
            "center_ll": [round(float(r.lat), 6), round(float(r.lon), 6)],
            "side_m": cfg["tile"]["side_m"],
            "label": f"{r.region} analog of {r.f2_best_course}",
            "region": r.region,
            "best_course": r.f2_best_course,
            "f2_dist": round(float(r.f2_dist), 4),
            "relaxed_tier": bool(getattr(r, "f1_relaxed", False)),
            "selected": False,
            "tile_scout": TILE_SCOUT_VERSION,
            "cfg_hash": sconfig.cfg_hash(cfg),
        }
    with open(man_p, "w") as f:
        json.dump(man, f, indent=1, sort_keys=True)
        f.write("\n")
    with open(txt_p, "w") as f:
        f.write("# Stage-0T natural-tile analogs — generated by "
                "`python3 -m tile_scout finalize`.\n"
                "# One key per line; details in tiles_us.json.\n")
        for k in sorted(man):
            f.write(k + "\n")
    print(f"wrote {txt_p} + {man_p}: {len(man)} tiles "
          f"({len(rows)} from this run)")
    return 0
