"""Curated parkland-course candidate list for the collector.

Each entry: (key, display_name, geocode_query, architect).  The 27 reference
courses are listed first (already in the cache from ``seed_reference.py`` — the
driver reuses those and does not re-fetch).  The rest are well-known, tree-lined
PARKLAND courses spread across relief bands and regions; links / desert /
heathland venues are deliberately avoided (and the canopy gate drops any that
slip through).  We over-list (~250+) so the ~200 target survives geocode/OSM
misses.  ``geocode_query`` is sent to Nominatim; keep it specific enough to land
on the right club.
"""

# Keys to REMOVE and never re-collect (user-requested removals + duplicate
# resolutions). collect.py deletes any cached entry here, skips it on collection,
# and omits it from the emitted atlas. For each duplicate group, the KEPT key is
# noted; the others are listed here.
EXCLUDE = {
    # --- user "to remove" (corrupted / unwanted land) ---
    "harbourtown", "harbour2",       # Harbour Town Golf Links (ref + dup)
    "durbancc",                      # Durban Country Club
    "essexon",                       # Essex Golf and Country Club (Ontario)
    "carnoustieburnside",            # Downfield Golf Club
    "estonia",                       # Estonian Golf and Country Club
    "theberkshire",                  # The Berkshire Red
    "hamburg",                       # Hamburger Golf-Club Falkenstein
    "malone",                        # Malone Golf Club
    "morfontaine",                   # Golf de Morfontaine
    "singapore",                     # Sentosa Golf Club Serapong
    "sunningdale2",                  # Sunningdale New Course
    "swinley",                       # Swinley Forest Golf Club
    "banff", "banff2",               # Fairmont Banff Springs (ref + dup)
    "fota",                          # Fota Island Resort
    "longcove",                      # Long Cove Club
    "royalcanberra",                 # Royal Canberra Golf Club
    # --- duplicate resolutions (keeper -> removed) ---
    "medinah3",                      # keep medinah
    "muirfieldoh",                   # keep muirfieldvillage
    "olympiafields", "olympiafields2",  # keep olympia (ref)
    "eastlake2",                     # keep eastlake (ref)
    "firestone2", "firestonenorth",  # keep firestone (ref)
    "quailhollow", "quailhollow2",   # keep quail (ref)
    "stgeorges2",                    # keep stgeorges
    "chapultepec2",                  # keep chapultepec (ref)
    "greenbrier2",                   # keep greenbrier (ref)
    "wentworth2", "wentworthw",      # keep wentworth (ref)
    "wingedfoot2",                   # keep wingedfoot (ref)
    "cherry2",                       # keep cherryhills (ref)
    "beckenbauer",                   # keep wittelsbacher (Munich Eichenried)
    "colonial2",                     # keep colonial (ref, Fort Worth)
    "wanamaker",                     # keep aronimink
    "bethpageblack",                 # keep bethpage (ref)
    "capital",                       # keep congressional (ref)
    "westhill",                      # keep worplesdon (identical collect — adjacent Surrey club)
}

# key, label, geocode query, architect
REFERENCE = [
    "oakmont", "quail", "congressional", "valhalla", "eastlake", "riviera",
    "augusta", "firestone", "wingedfoot", "wentworth", "sawgrass", "doral",
    "bethpage", "brookline", "golfnational", "bayhill", "colonial", "valderrama",
    "chapultepec", "jasper", "capilano", "banff", "cherryhills", "harbourtown",
    "olympia", "greenbrier", "crans",
]

# Newly collected candidates (parkland; over-listed).
CANDIDATES = [
    # ---- United States ----
    ("medinah", "Medinah Country Club", "Medinah Country Club, Illinois, USA", "Tom Bendelow, 1925"),
    ("oakhill", "Oak Hill Country Club", "Oak Hill Country Club, Rochester, New York, USA", "Donald Ross, 1926"),
    ("baltusrol", "Baltusrol Golf Club", "Baltusrol Golf Club, Springfield, New Jersey, USA", "A.W. Tillinghast, 1922"),
    ("merion", "Merion Golf Club", "Merion Golf Club, Ardmore, Pennsylvania, USA", "Hugh Wilson, 1912"),
    ("muirfieldvillage", "Muirfield Village Golf Club", "Muirfield Village Golf Club, Dublin, Ohio, USA", "Jack Nicklaus, 1974"),
    ("southernhills", "Southern Hills Country Club", "Southern Hills Country Club, Tulsa, Oklahoma, USA", "Perry Maxwell, 1936"),
    ("hazeltine", "Hazeltine National Golf Club", "Hazeltine National Golf Club, Chaska, Minnesota, USA", "Robert Trent Jones, 1962"),
    ("oaklandhills", "Oakland Hills Country Club", "Oakland Hills Country Club, Bloomfield, Michigan, USA", "Donald Ross, 1918"),
    ("interlachen", "Interlachen Country Club", "Interlachen Country Club, Edina, Minnesota, USA", "Donald Ross, 1919"),
    ("inverness", "Inverness Club", "Inverness Club, Toledo, Ohio, USA", "Donald Ross, 1919"),
    ("scioto", "Scioto Country Club", "Scioto Country Club, Columbus, Ohio, USA", "Donald Ross, 1916"),
    ("aronimink", "Aronimink Golf Club", "Aronimink Golf Club, Newtown Square, Pennsylvania, USA", "Donald Ross, 1928"),
    ("bellerive", "Bellerive Country Club", "Bellerive Country Club, St. Louis, Missouri, USA", "Robert Trent Jones, 1960"),
    ("crookedstick", "Crooked Stick Golf Club", "Crooked Stick Golf Club, Carmel, Indiana, USA", "Pete Dye, 1964"),
    ("torreypines", "Torrey Pines Golf Course", "Torrey Pines Golf Course, La Jolla, California, USA", "William Bell, 1957"),
    ("losangeles", "Los Angeles Country Club", "Los Angeles Country Club, California, USA", "George Thomas, 1921"),
    ("belair", "Bel-Air Country Club", "Bel-Air Country Club, Los Angeles, California, USA", "George Thomas, 1926"),
    ("olympicclub", "The Olympic Club", "The Olympic Club, San Francisco, California, USA", "Sam Whiting, 1924"),
    ("hardingpark", "TPC Harding Park", "Harding Park Golf Course, San Francisco, California, USA", "Willie Watson, 1925"),
    ("ridgewood", "Ridgewood Country Club", "Ridgewood Country Club, Paramus, New Jersey, USA", "A.W. Tillinghast, 1929"),
    ("plainfield", "Plainfield Country Club", "Plainfield Country Club, Edison, New Jersey, USA", "Donald Ross, 1921"),
    ("canterbury", "Canterbury Golf Club", "Canterbury Golf Club, Beachwood, Ohio, USA", "Herbert Strong, 1922"),
    ("victoria", "Victoria National Golf Club", "Victoria National Golf Club, Newburgh, Indiana, USA", "Tom Fazio, 1998"),
    ("quailhollow", "Quail Hollow Club", "Quail Hollow Club, Charlotte, North Carolina, USA", "George Cobb, 1961"),
    ("sedgefield", "Sedgefield Country Club", "Sedgefield Country Club, Greensboro, North Carolina, USA", "Donald Ross, 1926"),
    ("colonialct", "Colonial Country Club", "Colonial Country Club, Memphis, Tennessee, USA", ""),
    ("riverhighlands", "TPC River Highlands", "TPC River Highlands, Cromwell, Connecticut, USA", "Pete Dye, 1982"),
    ("congaree", "Congaree Golf Club", "Congaree Golf Club, Ridgeland, South Carolina, USA", "Tom Fazio, 2017"),
    ("caves", "Caves Valley Golf Club", "Caves Valley Golf Club, Owings Mills, Maryland, USA", "Tom Fazio, 1991"),
    ("baltimore", "Baltimore Country Club", "Baltimore Country Club, Timonium, Maryland, USA", "A.W. Tillinghast, 1926"),
    ("hamilton", "Hamilton Golf and Country Club", "Hamilton Golf and Country Club, Ancaster, Ontario, Canada", "Harry Colt, 1916"),
    ("stgeorges", "St. George's Golf and Country Club", "St. George's Golf and Country Club, Toronto, Ontario, Canada", "Stanley Thompson, 1929"),
    ("hamiltonwm", "Warwick Hills Golf and Country Club", "Warwick Hills Golf and Country Club, Grand Blanc, Michigan, USA", ""),
    ("brookside", "Brookside Golf Course", "Brookside Golf Course, Pasadena, California, USA", "William Bell, 1928"),
    ("cog", "Cog Hill Golf and Country Club", "Cog Hill Golf and Country Club, Lemont, Illinois, USA", "Dick Wilson, 1964"),
    ("browndeer", "Brown Deer Park Golf Course", "Brown Deer Park Golf Course, Milwaukee, Wisconsin, USA", ""),
    ("innisbrook", "Innisbrook Copperhead", "Innisbrook Resort, Palm Harbor, Florida, USA", "Larry Packard, 1972"),
    ("tpcboston", "TPC Boston", "TPC Boston, Norton, Massachusetts, USA", "Arnold Palmer, 2002"),
    ("nemacolin", "Nemacolin Country Club", "Nemacolin, Farmington, Pennsylvania, USA", ""),
    ("wakefield", "Wakefield Plantation", "TPC Wakefield Plantation, Raleigh, North Carolina, USA", "Hale Irwin, 2000"),
    ("sanantonio", "TPC San Antonio Oaks", "TPC San Antonio, San Antonio, Texas, USA", "Greg Norman, 2010"),
    ("colonial2", "Colonial Country Club Fort Worth", "Colonial Country Club, Fort Worth, Texas, USA", "John Bredemus, 1936"),
    ("detroit", "Detroit Golf Club", "Detroit Golf Club, Detroit, Michigan, USA", "Donald Ross, 1916"),
    ("bmw", "Conway Farms Golf Club", "Conway Farms Golf Club, Lake Forest, Illinois, USA", "Tom Fazio, 1991"),
    ("olympiafields", "Olympia Fields North", "Olympia Fields Country Club, Illinois, USA", "Willie Park Jr., 1922"),
    ("northberwick", "Sleepy Hollow Country Club", "Sleepy Hollow Country Club, Scarborough, New York, USA", "A.W. Tillinghast, 1911"),
    ("winged2", "Quaker Ridge Golf Club", "Quaker Ridge Golf Club, Scarsdale, New York, USA", "A.W. Tillinghast, 1918"),
    ("westchester", "Westchester Country Club", "Westchester Country Club, Rye, New York, USA", "Walter Travis, 1922"),
    ("hamilton3", "Country Club of Detroit", "Country Club of Detroit, Grosse Pointe, Michigan, USA", "Harry Colt, 1914"),
    ("nashville", "Belle Meade Country Club", "Belle Meade Country Club, Nashville, Tennessee, USA", ""),
    ("atlanta", "Atlanta Athletic Club", "Atlanta Athletic Club, Johns Creek, Georgia, USA", "Robert Trent Jones, 1967"),
    ("peachtree", "Peachtree Golf Club", "Peachtree Golf Club, Atlanta, Georgia, USA", "Robert Trent Jones, 1948"),
    ("capital", "Congressional Blue", "Congressional Country Club, Bethesda, Maryland, USA", "Devereux Emmet, 1924"),
    ("hershey", "Hershey Country Club", "Hershey Country Club, Hershey, Pennsylvania, USA", "Maurice McCarthy, 1930"),
    ("saucon", "Saucon Valley Country Club", "Saucon Valley Country Club, Bethlehem, Pennsylvania, USA", "Herbert Strong, 1922"),
    ("lehigh", "Lehigh Country Club", "Lehigh Country Club, Allentown, Pennsylvania, USA", "William Flynn, 1920"),
    ("rochester", "Country Club of Rochester", "Country Club of Rochester, New York, USA", "Donald Ross, 1911"),
    ("cherry2", "Cherry Hills Village", "Cherry Hills Country Club, Colorado, USA", "William Flynn, 1923"),
    ("broadmoor", "The Broadmoor East", "The Broadmoor Golf Club, Colorado Springs, Colorado, USA", "Donald Ross, 1918"),
    ("castlepines", "Castle Pines Golf Club", "Castle Pines Golf Club, Castle Rock, Colorado, USA", "Jack Nicklaus, 1981"),
    ("colorado", "Colorado Golf Club", "Colorado Golf Club, Parker, Colorado, USA", "Coore Crenshaw, 2007"),
    ("kingsmill", "Kingsmill River Course", "Kingsmill Resort, Williamsburg, Virginia, USA", "Pete Dye, 1975"),
    ("roberttrent", "Robert Trent Jones Golf Club", "Robert Trent Jones Golf Club, Gainesville, Virginia, USA", "RTJ, 1991"),
    ("sycamore", "Sycamore Hills Golf Club", "Sycamore Hills Golf Club, Fort Wayne, Indiana, USA", "Jack Nicklaus, 1989"),
    ("firestone2", "Firestone South", "Firestone Country Club, Akron, Ohio, USA", "Bert Way, 1929"),
    ("bayhill2", "Isleworth Country Club", "Isleworth Golf and Country Club, Windermere, Florida, USA", "Arnold Palmer, 1986"),
    ("laketahoe", "Edgewood Tahoe", "Edgewood Tahoe Golf Course, Stateline, Nevada, USA", "George Fazio, 1968"),
    # ---- United Kingdom & Ireland (parkland) ----
    ("wentworth2", "Wentworth East Course", "Wentworth Club, Virginia Water, Surrey, England", "Harry Colt, 1924"),
    ("theberkshire", "The Berkshire Red", "The Berkshire Golf Club, Ascot, Berkshire, England", "Herbert Fowler, 1928"),
    ("stgeorgeshill", "St George's Hill Golf Club", "St George's Hill Golf Club, Weybridge, Surrey, England", "Harry Colt, 1913"),
    ("swinley", "Swinley Forest Golf Club", "Swinley Forest Golf Club, Ascot, Berkshire, England", "Harry Colt, 1909"),
    ("thegrove", "The Grove", "The Grove, Chandler's Cross, Hertfordshire, England", "Kyle Phillips, 2003"),
    ("belfry", "The Belfry Brabazon", "The Belfry, Sutton Coldfield, England", "Dave Thomas, 1977"),
    ("celtic", "Celtic Manor Twenty Ten", "Celtic Manor Resort, Newport, Wales", "Ross McMurray, 2007"),
    ("lough", "Adare Manor", "Adare Manor Golf Course, Adare, County Limerick, Ireland", "Tom Fazio, 2017"),
    ("carton", "Carton House Montgomerie", "Carton House, Maynooth, County Kildare, Ireland", "Colin Montgomerie, 2003"),
    ("mountjuliet", "Mount Juliet Golf Course", "Mount Juliet Estate, Thomastown, County Kilkenny, Ireland", "Jack Nicklaus, 1991"),
    ("kclub", "The K Club Palmer", "The K Club, Straffan, County Kildare, Ireland", "Arnold Palmer, 1991"),
    ("druids", "Druids Glen Golf Club", "Druids Glen, Newtownmountkennedy, County Wicklow, Ireland", "Pat Ruddy, 1995"),
    ("wisley", "The Wisley", "The Wisley Golf Club, Surrey, England", "Robert Trent Jones, 1991"),
    ("sunningdale2", "Sunningdale New Course", "Sunningdale Golf Club, Berkshire, England", "Harry Colt, 1923"),
    ("woburn", "Woburn Marquess", "Woburn Golf Club, Milton Keynes, England", "Peter Alliss, 2000"),
    ("forestpines", "Forest Pines", "Forest Pines Golf Club, Broughton, Lincolnshire, England", ""),
    ("brabazon2", "Hanbury Manor", "Hanbury Manor, Ware, Hertfordshire, England", "Jack Nicklaus II, 1990"),
    ("lansdowne", "Slaley Hall Hunting Course", "Slaley Hall, Hexham, Northumberland, England", "Dave Thomas, 1988"),
    # ---- Continental Europe (parkland) ----
    ("valderrama2", "Real Club Valderrama", "Real Club Valderrama, Sotogrande, Spain", "Robert Trent Jones, 1974"),
    ("pgacatalunya", "PGA Catalunya Stadium", "PGA Catalunya Resort, Caldes de Malavella, Spain", "Neville-Green, 1999"),
    ("elsaler", "El Saler Golf", "Parador El Saler, Valencia, Spain", "Javier Arana, 1968"),
    ("puertahierro", "Real Club de la Puerta de Hierro", "Real Club de la Puerta de Hierro, Madrid, Spain", "Harry Colt, 1904"),
    ("chantilly", "Golf de Chantilly", "Golf de Chantilly, Vineuil-Saint-Firmin, France", "Tom Simpson, 1909"),
    ("morfontaine", "Golf de Morfontaine", "Golf de Morfontaine, Mortefontaine, France", "Tom Simpson, 1913"),
    ("fontainebleau", "Golf de Fontainebleau", "Golf de Fontainebleau, France", "Tom Simpson, 1909"),
    ("saintnom", "Saint-Nom-la-Bretèche", "Golf de Saint-Nom-la-Bretèche, France", "Fred Hawtree, 1959"),
    ("lesbordes", "Les Bordes Golf Club", "Les Bordes Golf International, Saint-Laurent-Nouan, France", "Robert von Hagge, 1986"),
    ("kennemer", "Kennemer Golf Club", "Kennemer Golf and Country Club, Zandvoort, Netherlands", "Harry Colt, 1927"),
    ("hilversum", "Hilversumsche Golf Club", "Hilversumsche Golf Club, Hilversum, Netherlands", "Harry Colt, 1910"),
    ("royalhague", "Koninklijke Haagsche", "Koninklijke Haagsche Golf and Country Club, Wassenaar, Netherlands", "Harry Colt, 1938"),
    ("frankfurt", "Golf Club Frankfurt", "Frankfurter Golf Club, Frankfurt, Germany", "Harry Colt, 1913"),
    ("hamburg", "Hamburger Golf-Club Falkenstein", "Hamburger Golf-Club Falkenstein, Hamburg, Germany", "Harry Colt, 1930"),
    ("koln", "Golf- und Land-Club Köln", "Golf- und Land-Club Köln, Bergisch Gladbach, Germany", "Bernhard von Limburger, 1962"),
    ("wittelsbacher", "Golfclub München Eichenried", "Golfclub München Eichenried, Germany", ""),
    ("crans2", "Crans-sur-Sierre Golf Club", "Crans-sur-Sierre Golf Club, Crans-Montana, Switzerland", "Harry Nicholson, 1906"),
    ("zurich", "Golf und Country Club Zürich", "Golf and Country Club Zürich, Zumikon, Switzerland", ""),
    ("milano", "Golf Club Milano", "Golf Club Milano, Monza, Italy", "Peter Gannon, 1928"),
    ("olgiata", "Olgiata Golf Club", "Circolo Golf Olgiata, Rome, Italy", "Charles Lawrie, 1961"),
    ("gardagolf", "Gardagolf Country Club", "Gardagolf Country Club, Soiano del Lago, Italy", "Cotton Pennink, 1985"),
    ("marcopolo", "Golf Club Villa d'Este", "Golf Club Villa d'Este, Montorfano, Italy", "Peter Gannon, 1926"),
    ("bogogno", "Circolo Golf Bogogno", "Circolo Golf Bogogno, Bogogno, Italy", "Robert von Hagge, 1997"),
    ("halmstad", "Halmstad Golfklubb", "Halmstad Golf Club, Tylösand, Sweden", "Rafael Sundblom, 1938"),
    ("bro", "Bro Hof Slott Stadium", "Bro Hof Slott Golf Club, Upplands-Bro, Sweden", "Robert Trent Jones Jr., 2007"),
    ("falsterbo", "Barsebäck Golf and Country Club", "Barsebäck Golf and Country Club, Sweden", "Ture Bruce, 1969"),
    ("oslo", "Oslo Golfklubb", "Oslo Golfklubb, Bogstad, Norway", "Tom Simpson, 1924"),
    ("helsinki", "Helsingin Golfklubi", "Helsingin Golfklubi, Tali, Helsinki, Finland", "Carl Hellström, 1932"),
    ("praha", "Golf Club Praha", "Golf Club Praha, Prague, Czechia", ""),
    ("karlstejn", "Karlštejn Golf Resort", "Golf Resort Karlštejn, Czechia", "Cotton Pennink, 1993"),
    ("vienna", "Golfclub Wien", "Golfclub Wien, Freudenau, Vienna, Austria", ""),
    ("fontana", "Fontana Golf Club", "Fontana Golf Club, Oberwaltersdorf, Austria", "Doug Carrick, 1997"),
    ("estoril", "Clube de Golf do Estoril", "Clube de Golf do Estoril, Portugal", "Mackenzie Ross, 1945"),
    ("penha", "Penha Longa Atlantic", "Penha Longa Resort, Sintra, Portugal", "Robert Trent Jones Jr., 1992"),
    ("quintalago", "Quinta do Lago South", "Quinta do Lago, Almancil, Portugal", "William Mitchell, 1974"),
    # ---- Canada (parkland) ----
    ("glenabbey", "Glen Abbey Golf Club", "Glen Abbey Golf Club, Oakville, Ontario, Canada", "Jack Nicklaus, 1976"),
    ("royalmontreal", "Royal Montreal Blue", "Royal Montreal Golf Club, Île Bizard, Quebec, Canada", "Dick Wilson, 1959"),
    ("beaconhall", "Beacon Hall Golf Club", "Beacon Hall Golf Club, Aurora, Ontario, Canada", "Bob Cupp, 1988"),
    ("nationalgc", "The National Golf Club of Canada", "The National Golf Club of Canada, Woodbridge, Ontario, Canada", "Tom Fazio, 1975"),
    ("devil", "Devil's Paintbrush", "Devil's Pulpit Golf Association, Caledon, Ontario, Canada", "Dana Fry, 1990"),
    ("redtail", "Redtail Golf Course", "Redtail Golf Course, Port Stanley, Ontario, Canada", "Donald Steel, 1992"),
    ("banffdup", "Stewart Creek Golf Club", "Stewart Creek Golf Club, Canmore, Alberta, Canada", "Gary Browning, 2000"),
    ("predator", "Predator Ridge Golf Resort", "Predator Ridge Golf Resort, Vernon, British Columbia, Canada", "Les Furber, 1991"),
    ("bigsky", "Big Sky Golf Club", "Big Sky Golf Club, Pemberton, British Columbia, Canada", "Bob Cupp, 1994"),
    # ---- Australia & New Zealand (parkland/sandbelt-adjacent) ----
    ("australian", "The Australian Golf Club", "The Australian Golf Club, Sydney, Australia", "Jack Nicklaus, 1977"),
    ("huntingdale", "Huntingdale Golf Club", "Huntingdale Golf Club, Melbourne, Australia", "Charles Alison, 1941"),
    ("metropolitan", "Metropolitan Golf Club", "Metropolitan Golf Club, Melbourne, Australia", "JB Mackenzie, 1908"),
    ("yarrayarra", "Yarra Yarra Golf Club", "Yarra Yarra Golf Club, Melbourne, Australia", "Alex Russell, 1929"),
    ("kingston", "Kingston Heath Golf Club", "Kingston Heath Golf Club, Melbourne, Australia", "Dan Soutar, 1925"),
    ("commonwealth", "Commonwealth Golf Club", "Commonwealth Golf Club, Melbourne, Australia", "Sloan Morpeth, 1920"),
    ("victoriaau", "Victoria Golf Club", "Victoria Golf Club, Melbourne, Australia", "Oscar Damman, 1927"),
    ("royalpines", "RACV Royal Pines Resort", "Royal Pines Resort, Gold Coast, Australia", "Graham Marsh, 1990"),
    ("brookwater", "Brookwater Golf Club", "Brookwater Golf and Country Club, Brisbane, Australia", "Greg Norman, 2002"),
    ("millbrook", "Millbrook Resort", "Millbrook Resort, Queenstown, New Zealand", "Bob Charles, 1993"),
    ("clearwater", "Clearwater Golf Club", "Clearwater Golf Club, Christchurch, New Zealand", "John Darby, 2001"),
    # ---- Asia (parkland) ----
    ("hirono", "Hirono Golf Club", "Hirono Golf Club, Miki, Hyogo, Japan", "Charles Alison, 1932"),
    ("kasumigaseki", "Kasumigaseki Country Club", "Kasumigaseki Country Club, Kawagoe, Saitama, Japan", "Kinya Fujita, 1929"),
    ("tokyo", "Tokyo Golf Club", "Tokyo Golf Club, Sayama, Saitama, Japan", "Charles Alison, 1940"),
    ("naruo", "Naruo Golf Club", "Naruo Golf Club, Kawanishi, Hyogo, Japan", "Crane Alison, 1920"),
    ("sheshan", "Sheshan International Golf Club", "Sheshan International Golf Club, Shanghai, China", "Nelson Haworth, 2004"),
    ("mission", "Mission Hills Shenzhen", "Mission Hills Golf Club, Shenzhen, China", "Jack Nicklaus, 1994"),
    ("nine", "Nine Bridges", "Club at Nine Bridges, Jeju, South Korea", "Ronald Fream, 2001"),
    ("blackstone", "Jack Nicklaus Golf Club Korea", "Jack Nicklaus Golf Club Korea, Incheon, South Korea", "Jack Nicklaus, 2010"),
    ("singapore", "Sentosa Golf Club Serapong", "Sentosa Golf Club, Singapore", "Ronald Fream, 1982"),
    ("bangkok", "Alpine Golf Club", "Alpine Golf and Sports Club, Pathum Thani, Thailand", "Ronald Fream, 1992"),
    ("delhi", "Delhi Golf Club", "Delhi Golf Club, New Delhi, India", "Peter Thomson, 1931"),
    # ---- South Africa & Latin America (parkland) ----
    ("houghton", "Houghton Golf Club", "Houghton Golf Club, Johannesburg, South Africa", "Robert Grimsdell, 1926"),
    ("glendower", "Glendower Golf Club", "Glendower Golf Club, Johannesburg, South Africa", "Charles Alison, 1937"),
    ("royaljhb", "Royal Johannesburg and Kensington", "Royal Johannesburg and Kensington Golf Club, South Africa", "Robert Grimsdell, 1933"),
    ("olivedale", "Olivedale", "Randpark Golf Club, Johannesburg, South Africa", ""),
    ("fancourt", "Fancourt Montagu", "Fancourt, George, South Africa", "Gary Player, 1989"),
    ("sanisidro", "Jockey Club Argentina", "Jockey Club, San Isidro, Buenos Aires, Argentina", "Alister MacKenzie, 1935"),
    ("olivos", "Olivos Golf Club", "Olivos Golf Club, Buenos Aires, Argentina", ""),
    ("gavea", "Gávea Golf and Country Club", "Gávea Golf and Country Club, Rio de Janeiro, Brazil", "Arthur Davidson, 1926"),
    ("saopaulo", "São Paulo Golf Club", "São Paulo Golf Club, São Paulo, Brazil", "Arthur Davidson, 1911"),
    ("chapultepec2", "Club de Golf Chapultepec", "Club de Golf Chapultepec, Mexico City, Mexico", "Willie Smith, 1921"),
    ("guadalajara", "Guadalajara Country Club", "Guadalajara Country Club, Mexico", ""),

    # ---- Wave 2 (broaden the pool toward ~200 kept) ----
    # US — classic clubs & tour venues
    ("pinehurst2", "Pinehurst No. 2", "Pinehurst Resort, Pinehurst, North Carolina, USA", "Donald Ross, 1907"),
    ("wingedfoot2", "Winged Foot Golf Club", "Winged Foot Golf Club, Mamaroneck, New York, USA", "A.W. Tillinghast, 1923"),
    ("nywoodmere", "Woodmere Club", "Woodmere Club, Woodmere, New York, USA", ""),
    ("garden", "Garden City Golf Club", "Garden City Golf Club, Garden City, New York, USA", "Walter Travis, 1899"),
    ("engineers", "Engineers Country Club", "Engineers Country Club, Roslyn Harbor, New York, USA", "Herbert Strong, 1917"),
    ("meadowbrook", "Meadow Brook Club", "Meadow Brook Club, Jericho, New York, USA", "Dick Wilson, 1955"),
    ("bethpageblack", "Bethpage State Park", "Bethpage State Park, Farmingdale, New York, USA", "A.W. Tillinghast, 1936"),
    ("tpccrooked", "Whistling Straits Irish", "Whistling Straits, Kohler, Wisconsin, USA", "Pete Dye, 1998"),
    ("blackwolf", "Blackwolf Run River", "Blackwolf Run, Kohler, Wisconsin, USA", "Pete Dye, 1988"),
    ("erin", "Erin Hills", "Erin Hills, Erin, Wisconsin, USA", "Hurdzan Fry, 2006"),
    ("sandvalley", "Sand Valley Golf Resort", "Sand Valley Golf Resort, Nekoosa, Wisconsin, USA", "Coore Crenshaw, 2017"),
    ("hazeltine2", "Hazeltine National", "Hazeltine National Golf Club, Chaska, Minnesota", "Robert Trent Jones, 1962"),
    ("windsong", "Windsong Farm Golf Club", "Windsong Farm Golf Club, Independence, Minnesota, USA", ""),
    ("spyglass", "Spyglass Hill Golf Course", "Spyglass Hill Golf Course, Pebble Beach, California, USA", "Robert Trent Jones, 1966"),
    ("poppyhills", "Poppy Hills Golf Course", "Poppy Hills Golf Course, Pebble Beach, California, USA", "Robert Trent Jones Jr., 1986"),
    ("pasatiempo", "Pasatiempo Golf Club", "Pasatiempo Golf Club, Santa Cruz, California, USA", "Alister MacKenzie, 1929"),
    ("olympicclub2", "Olympic Club Lake Course", "Olympic Club, Daly City, California, USA", "Sam Whiting, 1924"),
    ("sanfrancisco", "San Francisco Golf Club", "San Francisco Golf Club, San Francisco, California, USA", "A.W. Tillinghast, 1915"),
    ("stanford", "Stanford Golf Course", "Stanford Golf Course, Stanford, California, USA", "George Thomas, 1930"),
    ("olympiafields2", "Olympia Fields Country Club", "Olympia Fields Country Club, Olympia Fields, Illinois, USA", "Willie Park Jr., 1922"),
    ("medinah3", "Medinah Country Club No. 3", "Medinah Country Club, Medinah, Illinois, USA", "Tom Bendelow, 1928"),
    ("butlernational", "Butler National Golf Club", "Butler National Golf Club, Oak Brook, Illinois, USA", "George Fazio, 1974"),
    ("chicagoac", "Chicago Golf Club", "Chicago Golf Club, Wheaton, Illinois, USA", "C.B. Macdonald, 1895"),
    ("skokie", "Skokie Country Club", "Skokie Country Club, Glencoe, Illinois, USA", "Donald Ross, 1914"),
    ("northmoor", "Northmoor Country Club", "Northmoor Country Club, Highland Park, Illinois, USA", ""),
    ("shorehaven", "Shoreacres", "Shoreacres, Lake Bluff, Illinois, USA", "Seth Raynor, 1921"),
    ("brookhaven", "Brook Hollow Golf Club", "Brook Hollow Golf Club, Dallas, Texas, USA", "A.W. Tillinghast, 1920"),
    ("dallasnational", "Dallas National Golf Club", "Dallas National Golf Club, Dallas, Texas, USA", "Tom Fazio, 2002"),
    ("prestonwood", "Preston Trail Golf Club", "Preston Trail Golf Club, Dallas, Texas, USA", "Ralph Plummer, 1965"),
    ("champions", "Champions Golf Club Cypress Creek", "Champions Golf Club, Houston, Texas, USA", "Ralph Plummer, 1959"),
    ("houstonoaks", "Houston Country Club", "Houston Country Club, Houston, Texas, USA", "Robert Trent Jones, 1957"),
    ("austincc", "Austin Country Club", "Austin Country Club, Austin, Texas, USA", "Pete Dye, 1984"),
    ("crumpin", "Colonial Williamsburg Golden Horseshoe", "Golden Horseshoe Golf Club, Williamsburg, Virginia, USA", "Robert Trent Jones, 1963"),
    ("primland", "Primland Highland Course", "Primland, Meadows of Dan, Virginia, USA", "Donald Steel, 2006"),
    ("greenbrier2", "The Greenbrier Old White", "The Greenbrier, White Sulphur Springs, West Virginia, USA", "C.B. Macdonald, 1914"),
    ("pete", "Pete Dye Golf Club", "Pete Dye Golf Club, Bridgeport, West Virginia, USA", "Pete Dye, 1994"),
    ("firestonenorth", "Firestone North Course", "Firestone Country Club, Akron, Ohio, USA", "Robert Trent Jones, 1969"),
    ("muirfieldoh", "The Country Club at Muirfield Village", "The Country Club at Muirfield Village, Dublin, Ohio, USA", ""),
    ("doublesigle", "Double Eagle Club", "Double Eagle Club, Galena, Ohio, USA", "Weiskopf Morrish, 1992"),
    ("longaberger", "Longaberger Golf Club", "Longaberger Golf Club, Nashport, Ohio, USA", "Arthur Hills, 1999"),
    ("kirtland", "Kirtland Country Club", "Kirtland Country Club, Willoughby, Ohio, USA", "Charles Alison, 1921"),
    ("frenchlick", "French Lick Pete Dye Course", "French Lick Resort, French Lick, Indiana, USA", "Pete Dye, 2009"),
    ("valparaiso", "Sand Creek Country Club", "Sand Creek Country Club, Chesterton, Indiana, USA", ""),
    ("grandrapids", "Egypt Valley Country Club", "Egypt Valley Country Club, Ada, Michigan, USA", "Rees Jones, 1990"),
    ("crystal", "Crystal Downs Country Club", "Crystal Downs Country Club, Frankfort, Michigan, USA", "Alister MacKenzie, 1929"),
    ("forest", "Forest Dunes Golf Club", "Forest Dunes Golf Club, Roscommon, Michigan, USA", "Tom Weiskopf, 2002"),
    ("meadowbrookmi", "Meadowbrook Country Club", "Meadowbrook Country Club, Northville, Michigan, USA", ""),
    ("hillcrest", "Somerset Hills Country Club", "Somerset Hills Country Club, Bernardsville, New Jersey, USA", "A.W. Tillinghast, 1918"),
    ("pinevalley", "Pine Valley Golf Club", "Pine Valley Golf Club, Pine Valley, New Jersey, USA", "George Crump, 1918"),
    ("galloway", "Galloway National Golf Club", "Galloway National Golf Club, Galloway, New Jersey, USA", "Tom Fazio, 1995"),
    ("hollywood", "Hollywood Golf Club", "Hollywood Golf Club, Deal, New Jersey, USA", "Walter Travis, 1917"),
    ("mountainridge", "Mountain Ridge Country Club", "Mountain Ridge Country Club, West Caldwell, New Jersey, USA", "Donald Ross, 1929"),
    ("gulph", "Philadelphia Cricket Club Wissahickon", "Philadelphia Cricket Club, Flourtown, Pennsylvania, USA", "A.W. Tillinghast, 1922"),
    ("huntingdon", "Huntingdon Valley Country Club", "Huntingdon Valley Country Club, Huntingdon Valley, Pennsylvania, USA", "William Flynn, 1927"),
    ("rollingreen", "Rolling Green Golf Club", "Rolling Green Golf Club, Springfield, Pennsylvania, USA", "William Flynn, 1926"),
    ("gulfmills", "Gulph Mills Golf Club", "Gulph Mills Golf Club, King of Prussia, Pennsylvania, USA", "Donald Ross, 1919"),
    ("lancaster", "Lancaster Country Club", "Lancaster Country Club, Lancaster, Pennsylvania, USA", "William Flynn, 1920"),
    ("oakmont2", "Longue Vue Club", "Longue Vue Club, Verona, Pennsylvania, USA", "Robert White, 1921"),
    ("wanamaker", "Aronimink", "Aronimink Golf Club, Newtown Square, Pennsylvania, USA", "Donald Ross, 1928"),
    ("mayfield", "Mayfield Country Club", "Mayfield Country Club, South Euclid, Ohio, USA", "Bert Way, 1912"),
    ("brooklawn", "Brooklawn Country Club", "Brooklawn Country Club, Fairfield, Connecticut, USA", "A.W. Tillinghast, 1920"),
    ("wintonbury", "Wampanoag Country Club", "Wampanoag Country Club, West Hartford, Connecticut, USA", "Donald Ross, 1924"),
    ("newport", "Wannamoisett Country Club", "Wannamoisett Country Club, Rumford, Rhode Island, USA", "Donald Ross, 1914"),
    ("salem", "Salem Country Club", "Salem Country Club, Peabody, Massachusetts, USA", "Donald Ross, 1925"),
    ("essex", "Essex County Club", "Essex County Club, Manchester, Massachusetts, USA", "Donald Ross, 1917"),
    ("charlesriver", "Charles River Country Club", "Charles River Country Club, Newton, Massachusetts, USA", "Donald Ross, 1921"),
    ("kittansett", "The Kittansett Club", "The Kittansett Club, Marion, Massachusetts, USA", "William Flynn, 1922"),
    ("worcester", "Worcester Country Club", "Worcester Country Club, Worcester, Massachusetts, USA", "Donald Ross, 1914"),
    # US — South / Southeast
    ("eastlake2", "East Lake Golf Club", "East Lake Golf Club, Atlanta, Georgia, USA", "Donald Ross, 1913"),
    ("ansley", "Ansley Golf Club", "Ansley Golf Club, Atlanta, Georgia, USA", ""),
    ("druidhills", "Druid Hills Golf Club", "Druid Hills Golf Club, Atlanta, Georgia, USA", "H.H. Barker, 1912"),
    ("seaisland", "Sea Island Seaside", "Sea Island Golf Club, St. Simons Island, Georgia, USA", "Colt Alison, 1929"),
    ("ocean", "The Ocean Course Kiawah", "Kiawah Island Golf Resort, Kiawah Island, South Carolina, USA", "Pete Dye, 1991"),
    ("harbour2", "Harbour Town Golf Links", "Harbour Town Golf Links, Hilton Head Island, South Carolina, USA", "Pete Dye, 1969"),
    ("longcove", "Long Cove Club", "Long Cove Club, Hilton Head Island, South Carolina, USA", "Pete Dye, 1981"),
    ("quailhollow2", "Quail Hollow", "Quail Hollow Club, Charlotte, North Carolina, USA", "George Cobb, 1961"),
    ("charlottecc", "Charlotte Country Club", "Charlotte Country Club, Charlotte, North Carolina, USA", "Donald Ross, 1925"),
    ("oldtown", "Old Town Club", "Old Town Club, Winston-Salem, North Carolina, USA", "Perry Maxwell, 1939"),
    ("grandfather", "Grandfather Golf and Country Club", "Grandfather Golf and Country Club, Linville, North Carolina, USA", "Ellis Maples, 1968"),
    ("wadehampton", "Wade Hampton Golf Club", "Wade Hampton Golf Club, Cashiers, North Carolina, USA", "Tom Fazio, 1987"),
    ("mountainlake", "Mountain Lake", "Mountain Lake, Lake Wales, Florida, USA", "Seth Raynor, 1921"),
    ("seminole", "Seminole Golf Club", "Seminole Golf Club, Juno Beach, Florida, USA", "Donald Ross, 1929"),
    ("calusa", "Calusa Pines Golf Club", "Calusa Pines Golf Club, Naples, Florida, USA", "Hurdzan Fry, 2001"),
    ("streamsong", "Streamsong Blue", "Streamsong Resort, Bowling Green, Florida, USA", "Tom Doak, 2012"),
    ("bayhill3", "Bay Hill Club and Lodge", "Arnold Palmer's Bay Hill Club and Lodge, Orlando, Florida, USA", "Dick Wilson, 1961"),
    # Canada — extra
    ("stgeorges2", "St. George's Golf and Country Club", "St. George's Golf and Country Club, Etobicoke, Ontario, Canada", "Stanley Thompson, 1929"),
    ("scarboro", "Scarboro Golf and Country Club", "Scarboro Golf and Country Club, Toronto, Ontario, Canada", "A.W. Tillinghast, 1912"),
    ("toronto", "Toronto Golf Club", "Toronto Golf Club, Mississauga, Ontario, Canada", "Harry Colt, 1912"),
    ("lambton", "Lambton Golf and Country Club", "Lambton Golf and Country Club, Toronto, Ontario, Canada", "Willie Park Jr., 1902"),
    ("essexon", "Essex Golf and Country Club", "Essex Golf and Country Club, LaSalle, Ontario, Canada", "Donald Ross, 1929"),
    ("capilano2", "Capilano Golf and Country Club", "Capilano Golf and Country Club, West Vancouver, British Columbia, Canada", "Stanley Thompson, 1937"),
    ("shaughnessy", "Shaughnessy Golf and Country Club", "Shaughnessy Golf and Country Club, Vancouver, British Columbia, Canada", "A. Vernon Macan, 1960"),
    ("banff2", "Banff Springs Golf Course", "Fairmont Banff Springs Golf Course, Banff, Alberta, Canada", "Stanley Thompson, 1928"),
    ("jasperpark", "Jasper Park Lodge Golf Course", "Jasper Park Lodge Golf Course, Jasper, Alberta, Canada", "Stanley Thompson, 1925"),
    ("kananaskis", "Kananaskis Country Golf Course", "Kananaskis Country Golf Course, Kananaskis, Alberta, Canada", "Robert Trent Jones, 1983"),
    # UK & Ireland — extra parkland
    ("wentworthw", "Wentworth West Course", "Wentworth Club, Virginia Water, Surrey, England", "Harry Colt, 1926"),
    ("queenwood", "Queenwood Golf Club", "Queenwood Golf Club, Ottershaw, Surrey, England", "David McLay Kidd, 2001"),
    ("foxhills", "Foxhills Club and Resort", "Foxhills Club and Resort, Ottershaw, Surrey, England", "Fred Hawtree, 1975"),
    ("moor", "Moor Park Golf Club", "Moor Park Golf Club, Rickmansworth, Hertfordshire, England", "Harry Colt, 1923"),
    ("brocket", "Brocket Hall Melbourne", "Brocket Hall, Welwyn, Hertfordshire, England", "Peter Alliss, 1992"),
    ("frilford", "Frilford Heath Golf Club", "Frilford Heath Golf Club, Abingdon, Oxfordshire, England", ""),
    ("stmellion", "St Mellion Nicklaus Course", "St Mellion Estate, Saltash, Cornwall, England", "Jack Nicklaus, 1988"),
    ("gleneagles", "Gleneagles King's Course", "Gleneagles Hotel, Auchterarder, Scotland", "James Braid, 1919"),
    ("loch", "Loch Lomond Golf Club", "Loch Lomond Golf Club, Luss, Scotland", "Weiskopf Morrish, 1994"),
    ("blairgowrie", "Blairgowrie Rosemount", "Blairgowrie Golf Club, Blairgowrie, Scotland", "James Braid, 1934"),
    ("carnoustieburnside", "Downfield Golf Club", "Downfield Golf Club, Dundee, Scotland", "James Braid, 1932"),
    ("mountjuliet2", "Mount Juliet Estate", "Mount Juliet, Thomastown, County Kilkenny, Ireland", "Jack Nicklaus, 1991"),
    ("fota", "Fota Island Resort", "Fota Island Resort, Cork, Ireland", "Christy O'Connor Jnr, 1993"),
    ("powerscourt", "Powerscourt East Course", "Powerscourt Golf Club, Enniskerry, County Wicklow, Ireland", "Peter McEvoy, 1996"),
    ("malone", "Malone Golf Club", "Malone Golf Club, Belfast, Northern Ireland", "Fred Hawtree, 1962"),
    # Continental Europe — extra parkland
    ("sanroque", "San Roque Club Old Course", "San Roque Club, San Roque, Spain", "Dave Thomas, 1990"),
    ("montecastillo", "Montecastillo Golf", "Montecastillo Barceló, Jerez, Spain", "Jack Nicklaus, 1992"),
    ("laquinta", "La Quinta Golf", "La Quinta Golf, Marbella, Spain", "Manuel Piñero, 1989"),
    ("terramar", "Club de Golf Terramar", "Club de Golf Terramar, Sitges, Spain", ""),
    ("golfitaliano", "Circolo Golf Torino", "Circolo Golf Torino La Mandria, Fiano, Italy", "John Morrison, 1958"),
    ("islamallorca", "Golf Son Muntaner", "Golf Son Muntaner, Palma, Mallorca, Spain", "Kurt Rossknecht, 2000"),
    ("chamonix", "Golf Club de Chamonix", "Golf Club de Chamonix, Chamonix, France", "Robert Trent Jones, 1934"),
    ("evian", "Evian Resort Golf Club", "Evian Resort Golf Club, Évian-les-Bains, France", "Cabell Robinson, 1990"),
    ("terredargent", "Golf du Médoc Châteaux", "Golf du Médoc Resort, Le Pian-Médoc, France", "Bill Coore, 1989"),
    ("sperone", "Sporting Club de Bordeaux", "Golf de Bordeaux-Lac, Bordeaux, France", ""),
    ("valgardena", "Golf Club Petersberg", "Golf Club Petersberg, Nova Ponente, Italy", ""),
    ("berlin", "Golf- und Land-Club Berlin-Wannsee", "Golf- und Land-Club Berlin-Wannsee, Berlin, Germany", ""),
    ("stleon", "Golf Club St. Leon-Rot", "Golf Club St. Leon-Rot, St. Leon-Rot, Germany", "Dave Thomas, 1997"),
    ("beckenbauer", "Golfclub München Nord-Eichenried", "Golfclub München Eichenried, Eichenried, Germany", ""),
    ("gutlaerchenhof", "Golfclub Gut Lärchenhof", "Golfclub Gut Lärchenhof, Pulheim, Germany", "Jack Nicklaus, 1997"),
    ("brussels", "Royal Golf Club de Belgique", "Royal Golf Club de Belgique, Tervuren, Belgium", "Tom Simpson, 1906"),
    ("ravenstein", "Golf de Ravenstein", "Royal Golf Club de Belgique Ravenstein, Tervuren, Belgium", ""),
    ("dutch", "The Dutch", "The Dutch Golf Club, Spijk, Netherlands", "Colin Montgomerie, 2013"),
    ("estonia", "Estonian Golf and Country Club", "Estonian Golf and Country Club, Jõelähtme, Estonia", "Lassi-Pekka Tilander, 2005"),
    ("pinecliffs", "Pine Cliffs Golf", "Pine Cliffs Resort, Albufeira, Portugal", ""),
    ("montado", "Montado Golf Resort", "Montado Hotel and Golf Resort, Palmela, Portugal", ""),
    # Australia / NZ — extra
    ("royalmelbourne", "Royal Melbourne Golf Club", "Royal Melbourne Golf Club, Black Rock, Victoria, Australia", "Alister MacKenzie, 1926"),
    ("royaladelaide", "Royal Adelaide Golf Club", "Royal Adelaide Golf Club, Seaton, South Australia, Australia", "Alister MacKenzie, 1926"),
    ("newsouthwales", "New South Wales Golf Club", "New South Wales Golf Club, La Perouse, Sydney, Australia", "Alister MacKenzie, 1928"),
    ("royalcanberra", "Royal Canberra Golf Club", "Royal Canberra Golf Club, Canberra, Australia", ""),
    ("thelakes", "The Lakes Golf Club", "The Lakes Golf Club, Sydney, Australia", ""),
    ("peninsulakingswood", "Peninsula Kingswood Country Golf Club", "Peninsula Kingswood Country Golf Club, Frankston, Victoria, Australia", ""),
    ("woodlands", "Woodlands Golf Club", "Woodlands Golf Club, Mordialloc, Victoria, Australia", ""),
    ("cape", "Cape Kidnappers", "Cape Kidnappers Golf Course, Hawke's Bay, New Zealand", "Tom Doak, 2004"),
    ("jacks", "Jack's Point", "Jack's Point Golf Course, Queenstown, New Zealand", "John Darby, 2008"),
    # Japan / Korea / Asia — extra
    ("kawana", "Kawana Hotel Fuji Course", "Kawana Hotel Golf Course, Ito, Shizuoka, Japan", "Charles Alison, 1936"),
    ("abiko", "Abiko Golf Club", "Abiko Golf Club, Abiko, Chiba, Japan", ""),
    ("sagamihara", "Sagamihara Golf Club", "Sagamihara Golf Club, Sagamihara, Kanagawa, Japan", ""),
    ("classic", "The Classic Golf Club Japan", "The Classic Golf Club, Fukuoka, Japan", "Jack Nicklaus, 1994"),
    ("phoenix", "Phoenix Country Club", "Phoenix Country Club, Miyazaki, Japan", ""),
    ("ferncliff", "Pinx Golf Club", "Pinx Golf Club, Jeju, South Korea", "Theodore Robinson, 1992"),
    ("anyang", "Anyang Country Club", "Anyang Country Club, Gunpo, South Korea", ""),
    ("springcity", "Spring City Golf Lake Course", "Spring City Golf and Lake Resort, Kunming, China", "Jack Nicklaus, 1998"),
    ("hongkong", "Hong Kong Golf Club Fanling", "Hong Kong Golf Club, Fanling, Hong Kong", ""),
    ("bali", "Bali National Golf Club", "Bali National Golf Club, Nusa Dua, Indonesia", ""),
    ("thai", "Thai Country Club", "Thai Country Club, Chachoengsao, Thailand", "Denis Griffiths, 1996"),
    # South Africa / South America — extra
    ("leopard", "Leopard Creek Country Club", "Leopard Creek Country Club, Malelane, South Africa", "Gary Player, 1996"),
    ("durbancc", "Durban Country Club", "Durban Country Club, Durban, South Africa", "Laurie Waters, 1922"),
    ("erinvale", "Erinvale Golf Club", "Erinvale Golf Club, Somerset West, South Africa", "Gary Player, 1995"),
    ("stellenbosch", "Stellenbosch Golf Club", "Stellenbosch Golf Club, Stellenbosch, South Africa", ""),
    ("cordoba", "Córdoba Golf Club", "Córdoba Golf Club, Villa Allende, Argentina", "Mackenzie, 1935"),
    ("laredo", "Los Leones Golf Club", "Club de Golf Los Leones, Santiago, Chile", ""),
    ("terravista", "Terravista Golf Course", "Terravista Golf Course, Trancoso, Bahia, Brazil", "Dan Blankenship, 2004"),

    # ---- Wave 3 (reliable inland parkland backfill) ----
    ("thegolfclub", "The Golf Club", "The Golf Club, New Albany, Ohio, USA", "Pete Dye, 1967"),
    ("ncr", "NCR Country Club South", "NCR Country Club, Kettering, Ohio, USA", "Dick Wilson, 1954"),
    ("camargo", "Camargo Club", "Camargo Club, Cincinnati, Ohio, USA", "Seth Raynor, 1925"),
    ("honors", "The Honors Course", "The Honors Course, Ooltewah, Tennessee, USA", "Pete Dye, 1983"),
    ("kinloch", "Kinloch Golf Club", "Kinloch Golf Club, Manakin-Sabot, Virginia, USA", "Lester George, 2001"),
    ("ccvirginia", "Country Club of Virginia James River", "Country Club of Virginia, Richmond, Virginia, USA", "William Flynn, 1928"),
    ("sagevalley", "Sage Valley Golf Club", "Sage Valley Golf Club, Graniteville, South Carolina, USA", "Tom Fazio, 2001"),
    ("tpctwincities", "TPC Twin Cities", "TPC Twin Cities, Blaine, Minnesota, USA", "Arnold Palmer, 2000"),
    ("bostongc", "Boston Golf Club", "Boston Golf Club, Hingham, Massachusetts, USA", "Gil Hanse, 2004"),
    ("hamiltonfarm", "Hamilton Farm Golf Club", "Hamilton Farm Golf Club, Gladstone, New Jersey, USA", "Tom Fazio, 1999"),

    # ---- Wave 4 (backfill to ~200; distinct clubs, checked against kept set) ----
    # US
    ("oaktree", "Oak Tree National", "Oak Tree National, Edmond, Oklahoma, USA", "Pete Dye, 1976"),
    ("montclair", "Montclair Golf Club", "Montclair Golf Club, West Orange, New Jersey, USA", "Donald Ross, 1915"),
    ("canoebrook", "Canoe Brook Country Club", "Canoe Brook Country Club, Summit, New Jersey, USA", "Devereux Emmet, 1901"),
    ("piping", "Piping Rock Club", "Piping Rock Club, Locust Valley, New York, USA", "C.B. Macdonald, 1913"),
    ("creekclub", "The Creek Club", "The Creek Club, Locust Valley, New York, USA", "C.B. Macdonald, 1923"),
    ("fenway", "Fenway Golf Club", "Fenway Golf Club, Scarsdale, New York, USA", "A.W. Tillinghast, 1924"),
    ("buffalocc", "Country Club of Buffalo", "Country Club of Buffalo, Williamsville, New York, USA", "Donald Ross, 1926"),
    ("onwentsia", "Onwentsia Club", "Onwentsia Club, Lake Forest, Illinois, USA", "H.J. Tweedie, 1898"),
    ("knollwood", "Knollwood Club", "Knollwood Club, Lake Forest, Illinois, USA", "Charles Alison, 1924"),
    ("exmoor", "Exmoor Country Club", "Exmoor Country Club, Highland Park, Illinois, USA", ""),
    ("glenview", "Glen View Club", "Glen View Club, Golf, Illinois, USA", "Donald Ross, 1899"),
    ("minikahda", "The Minikahda Club", "The Minikahda Club, Minneapolis, Minnesota, USA", "Donald Ross, 1917"),
    ("woodhill", "Woodhill Country Club", "Woodhill Country Club, Wayzata, Minnesota, USA", "Donald Ross, 1916"),
    ("kenwood", "Kenwood Country Club", "Kenwood Country Club, Cincinnati, Ohio, USA", "William Diddel, 1930"),
    ("moraine", "Moraine Country Club", "Moraine Country Club, Dayton, Ohio, USA", "Alister MacKenzie, 1930"),
    ("franklinhills", "Franklin Hills Country Club", "Franklin Hills Country Club, Franklin, Michigan, USA", "Donald Ross, 1926"),
    ("bartonhills", "Barton Hills Country Club", "Barton Hills Country Club, Ann Arbor, Michigan, USA", "Donald Ross, 1919"),
    ("sunnehanna", "Sunnehanna Country Club", "Sunnehanna Country Club, Johnstown, Pennsylvania, USA", "A.W. Tillinghast, 1920"),
    ("wilmington", "Wilmington Country Club South", "Wilmington Country Club, Wilmington, Delaware, USA", "Robert Trent Jones, 1960"),
    ("dupont", "DuPont Country Club", "DuPont Country Club, Wilmington, Delaware, USA", ""),
    # UK / Ireland
    ("ganton", "Ganton Golf Club", "Ganton Golf Club, Ganton, North Yorkshire, England", "Harry Vardon, 1891"),
    ("littleaston", "Little Aston Golf Club", "Little Aston Golf Club, Sutton Coldfield, England", "Harry Vardon, 1908"),
    ("notts", "Notts Golf Club Hollinwell", "Notts Golf Club, Kirkby in Ashfield, England", "Willie Park Jr., 1901"),
    ("worplesdon", "Worplesdon Golf Club", "Worplesdon Golf Club, Woking, Surrey, England", "John Abercromby, 1908"),
    ("westhill", "West Hill Golf Club", "West Hill Golf Club, Brookwood, Surrey, England", "Willie Park Jr., 1909"),
    ("coombehill", "Coombe Hill Golf Club", "Coombe Hill Golf Club, Kingston upon Thames, England", "J.F. Abercromby, 1911"),
    ("royalwimbledon", "Royal Wimbledon Golf Club", "Royal Wimbledon Golf Club, London, England", "Harry Colt, 1907"),
    ("camberley", "Camberley Heath Golf Club", "Camberley Heath Golf Club, Camberley, Surrey, England", "Harry Colt, 1913"),
    ("hindhead", "Hindhead Golf Club", "Hindhead Golf Club, Hindhead, Surrey, England", ""),
    ("ferndown", "Ferndown Golf Club", "Ferndown Golf Club, Ferndown, Dorset, England", "Harold Hilton, 1913"),
    # Canada
    ("rosedale", "Rosedale Golf Club", "Rosedale Golf Club, Toronto, Ontario, Canada", "Donald Ross, 1912"),
    ("mississaugua", "Mississaugua Golf and Country Club", "Mississaugua Golf and Country Club, Mississauga, Ontario, Canada", "Percy Barrett, 1906"),
    ("weston", "Weston Golf and Country Club", "Weston Golf and Country Club, Toronto, Ontario, Canada", "Willie Park Jr., 1920"),
    ("summitgc", "Summit Golf and Country Club", "Summit Golf and Country Club, Richmond Hill, Ontario, Canada", "Stanley Thompson, 1912"),
    ("kanawaki", "Kanawaki Golf Club", "Kanawaki Golf Club, Kahnawake, Quebec, Canada", "Willie Park Jr., 1913"),
    # Europe
    ("sotogrande", "Real Club de Golf Sotogrande", "Real Club de Golf Sotogrande, San Roque, Spain", "Robert Trent Jones, 1964"),
    ("pedrena", "Real Golf de Pedreña", "Real Golf de Pedreña, Pedreña, Cantabria, Spain", "Harry Colt, 1928"),
    ("neguri", "Real Sociedad de Golf de Neguri", "Real Sociedad de Golf de Neguri, Getxo, Spain", "Javier Arana, 1961"),
    ("geneva", "Golf Club de Genève", "Golf Club de Genève, Cologny, Switzerland", "Robert Trent Jones, 1973"),
    ("joyenval", "Golf de Joyenval", "Golf de Joyenval, Chambourcy, France", "Robert Trent Jones, 1992"),
    # Australia
    ("royalsydney", "Royal Sydney Golf Club", "Royal Sydney Golf Club, Rose Bay, Sydney, Australia", "Thomas Bendelow, 1906"),
    ("lakekarrinyup", "Lake Karrinyup Country Club", "Lake Karrinyup Country Club, Perth, Western Australia", "Alex Russell, 1928"),
    ("concordau", "Concord Golf Club", "Concord Golf Club, Concord, Sydney, Australia", ""),
    ("grange", "The Grange Golf Club", "The Grange Golf Club, Adelaide, South Australia", ""),
    # replacement for the West Hill/Worplesdon collision (well-separated clubs)
    ("moortown", "Moortown Golf Club", "Moortown Golf Club, Leeds, England", "Alister MacKenzie, 1909"),
    ("apawamis", "The Apawamis Club", "The Apawamis Club, Rye, New York, USA", "Willie Dunn, 1899"),
]
