//! D2 port-parity: the Rust flow kernel must be behaviorally identical to
//! `tools/macro_campaign/macro_campaign/flow.py` + `metrics.core.fill_depressions`.
//!
//! Fixtures are generated by the Python originals (see
//! `fixtures/flow_parity/meta.txt`):
//! - a 128² 8 m crop of a real piedmont tile — exercises fill + steepest
//!   descent end-to-end (the eps-graded fill leaves no exact ties, so the
//!   flat BFS never fires here);
//! - a synthetic L-spill plateau fed straight to `receivers` — 3 488 cells
//!   resolve through the wave BFS, so wave order and D8 tie-breaking are
//!   both load-bearing.
//!
//! Everything is compared EXACTLY (bit-equal f64, equal indices). If this
//! test fails after an edit to `flow.rs`, the port has drifted from the
//! measured original — fix the port, never the fixture.

use course_world::flow;
use course_world::grid::{Grid, GridSpec};
use course_world::math::Vec2;

const DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/flow_parity");

fn read_f64(name: &str, n: usize) -> Vec<f64> {
    let bytes = std::fs::read(format!("{DIR}/{name}")).unwrap();
    assert_eq!(bytes.len(), n * 8, "{name}");
    bytes
        .chunks_exact(8)
        .map(|c| f64::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

fn read_i64(name: &str, n: usize) -> Vec<i64> {
    let bytes = std::fs::read(format!("{DIR}/{name}")).unwrap();
    assert_eq!(bytes.len(), n * 8, "{name}");
    bytes
        .chunks_exact(8)
        .map(|c| i64::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

fn grid_of(data: Vec<f64>, side: usize, cell: f64) -> Grid<f64> {
    Grid {
        spec: GridSpec::new(Vec2::new(0.0, 0.0), cell, side as u32, side as u32),
        data,
    }
}

#[test]
fn real_tile_crop_parity() {
    let n = 128 * 128;
    let z = grid_of(read_f64("z.f64", n), 128, 8.0);

    let filled = flow::fill_depressions(&z);
    let want_filled = read_f64("filled.f64", n);
    let diff = filled
        .data
        .iter()
        .zip(&want_filled)
        .filter(|(a, b)| a.to_bits() != b.to_bits())
        .count();
    assert_eq!(diff, 0, "filled surface diverges on {diff} cells");

    let (rec, slope) = flow::receivers(&filled, 8.0);
    assert_eq!(rec, read_i64("rec.i64", n), "receiver indices diverge");
    let want_slope = read_f64("slope.f64", n);
    let sdiff = slope
        .iter()
        .zip(&want_slope)
        .filter(|(a, b)| a.to_bits() != b.to_bits())
        .count();
    assert_eq!(sdiff, 0, "slopes diverge on {sdiff} cells");

    assert_eq!(flow::accumulate(&rec), read_i64("acc.i64", n), "accumulation diverges");
}

#[test]
fn plateau_flat_bfs_parity() {
    let n = 64 * 64;
    let z = grid_of(read_f64("plateau_z.f64", n), 64, 8.0);
    let (rec, slope) = flow::receivers(&z, 8.0);
    assert_eq!(rec, read_i64("plateau_rec.i64", n), "flat-BFS receivers diverge");
    assert_eq!(
        flow::accumulate(&rec),
        read_i64("plateau_acc.i64", n),
        "flat-BFS accumulation diverges"
    );
    // sanity: the BFS actually ran (matches the Python-side count)
    let resolved = rec
        .iter()
        .zip(&slope)
        .filter(|(r, s)| **r >= 0 && **s == 0.0)
        .count();
    assert_eq!(resolved, 3488, "flat coverage changed — regenerate fixtures");
}
