//! Seed → `TerrainParams`: the course-style sampler.
//!
//! Draws a full parameter set by resampling the **calibrated p(θ) ensemble** —
//! the density-ratio-weighted design points fit (in `tools/calibration`) so the
//! generator's metric distribution matches the 200-course Parkland Atlas, scored
//! by the same metric code (`tools/metrics`). The ensemble is baked into
//! `sampler/ptheta.rs` (generated by `python3 -m calibration.export_sampler`).
//!
//! The draw: one `DetRng` stream per seed picks a design point by its p(θ)
//! weight (inverse-CDF), adds small Gaussian jitter in unit space (continuity
//! between the members), and decodes each of the 19 knobs to real units — the
//! same `unit → θ` map the calibration used (`PSPEC`). Every morphology knob
//! (amplitude, spectrum, warp, redistribution, the detail/anisotropy band,
//! the landform-organization pair `ridged_mix`/`relief_patchiness`, and
//! erosion intensity/deposition/hardness/diffusion) comes straight from p(θ);
//! nothing is solved analytically anymore (v8 solved amplitude from a target
//! relief — v9+ draws it). v10 additionally matches the landform-ORGANIZATION
//! axes (roughness concentration, extrema granularity, valley coherence) and
//! reweights the ensemble along the relief axis so the fit's relief
//! distribution lands on the atlas (median 19.8 m).
//!
//! Two things sit *outside* p(θ), by design:
//!   - **Water** (rivers/lakes/coverage) — excluded from the morphology
//!     calibration; still drawn from its own atlas fit (`sample_water`), fed a
//!     forward *relief estimate* derived from the drawn knobs via the K-tables.
//!   - **The lowland lake-field period shrink** — a water-serving mechanism
//!     (hole-scale closed basins → the ~20% lowland lake fields) layered on the
//!     p(θ) wavelength; see `LOWLAND_PERIOD_SHRINK`.
//!
//! Deterministic throughout: `DetRng` + an Irwin–Hall normal (pure arithmetic),
//! and libm-backed `math::pow` in the decode, so the draw is bit-identical
//! cross-platform.

use crate::erosion::ErosionParams;
use crate::params::TerrainParams;
use crate::water::WaterParams;
use golf_core::det::DetRng;
use golf_core::math;

mod ptheta;
mod tables;
use ptheta::{NP, NPTS, PSPEC, PTHETA_CDF, PTHETA_U};
use tables::{
    CAL_ERODE_P, CAL_ERODE_T, CAL_GAINS, CAL_PERIODS, CAL_REDIST, K_ERODE, K_REDIST, K_RELIEF,
    SKEW_REDIST,
};

/// Bump when the sampler distribution changes — invalidates cached search
/// results and the pipeline/routing/holes goldens. v9 = full re-fit to the
/// calibrated p(θ) ensemble (17 knobs incl. the detail band + anisotropy +
/// reactivated hardness); replaces the analytic relief-mixture draws of v8.
/// v10 = the landform-organization re-fit: 19 knobs (+ridged_mix,
/// +relief_patchiness), matched on the 5 new organization axes, with a
/// relief-axis reweight (fit median 19.8 == atlas).
pub const SAMPLER_VERSION: u32 = 10;

/// Which mixture mode a draw came from (a label, not a hard class — the
/// distributions overlap).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ReliefMode {
    Lowland,
    Rolling,
    Mountain,
}

impl ReliefMode {
    pub fn label(self) -> &'static str {
        match self {
            ReliefMode::Lowland => "lowland",
            ReliefMode::Rolling => "rolling",
            ReliefMode::Mountain => "mountain",
        }
    }
}

/// A sampled parameter set plus the (now-derived) descriptive targets.
#[derive(Clone, Copy, Debug)]
pub struct SampledParams {
    pub seed: u64,
    /// Relief band label, derived from the forward relief estimate (reporting).
    pub mode: ReliefMode,
    /// Forward p2–p98 relief estimate over the 2 km world, meters — derived from
    /// the drawn knobs via the K-tables (feeds the water sampler + reporting;
    /// v8 *solved* amplitude to hit this, v9 draws amplitude and estimates it).
    pub relief_target: f64,
    /// Forward height-skewness estimate from the drawn redistribution exponent
    /// (reporting; positive = basin-and-hills, negative = plateau-and-valleys).
    pub skew_target: f64,
    pub params: TerrainParams,
    /// Erosion axes (intensity/deposition/hardness/diffusion), from p(θ).
    pub erosion: ErosionParams,
    /// Water axes, drawn from their own stream (`water-sampler-v1`) — outside the
    /// morphology calibration's scope.
    pub water: WaterParams,
}

// ---------------------------------------------------------------------------
// Constants. The p(θ) ensemble lives in `sampler/ptheta.rs` (generated by
// `python3 -m calibration.export_sampler`); the pipeline K-tables in
// `sampler/tables.rs` (generated by `xtask calibrate`).
// ---------------------------------------------------------------------------

/// Unit-space jitter (Gaussian sd) added to a resampled design point, for
/// continuity between the 512 discrete p(θ) members. Matches the calibration's
/// round-trip `sample_courses` jitter; tiny, so draws stay in-distribution.
const PTHETA_JITTER: f64 = 0.03;

/// Lowland feature-wavelength shrink (× (1 − this·lowland_k)) — THE lake-field
/// mechanism, preserved across the p(θ) re-fit as a water-serving adjustment on
/// the drawn wavelength. Floodable basin capacity scales inversely with the
/// period (`xtask lake-capacity`: ~20%+ qualifying area at P 500–900 vs 3–9% at
/// P ≥ 1400), giving golf-hole-scale (~300–700 m) lowland lakes.
const LOWLAND_PERIOD_SHRINK: f64 = 0.5;
/// Median terrain-water coverage % for deep-lowland lake fields. Drawn above the
/// nominal 20% target: realization pays a few points of friction (per-body caps,
/// connectivity guard, size/proportion culls).
const LOWLAND_COV_MED: f64 = 22.0;

/// Base-period clamp (m). The p(θ) draw already lives inside this band; the
/// clamp guards the post-draw lowland shrink. Lower bound 200 matches the
/// widened calibration schema (short-period designs fix the variogram_range
/// starvation).
const PERIOD_CLAMP: (f64, f64) = (200.0, 2200.0);

/// Smallest feature the octave rule (`octaves_for`, still used by
/// `xtask calibrate`) resolves, meters. Fine texture now comes from the detail
/// band + erosion, not from base octaves.
const MIN_FEATURE_M: f64 = 70.0;

// ---------------------------------------------------------------------------

/// Sample the full parameter set for a seed by drawing from the calibrated
/// p(θ) ensemble (see module docs).
pub fn sample_params(seed: u64) -> SampledParams {
    let mut rng = DetRng::new(seed, b"terrain-sampler-v1");

    // 1. Draw a unit-space θ: weighted resample of a design point + jitter.
    let u = draw_theta_unit(&mut rng);

    // 2. Decode the 17 knobs to real units (order = PSPEC / param_schema.NAMES).
    let amplitude = decode(0, u[0]);
    let base_period0 = decode(1, u[1]);
    let octaves = decode(2, u[2]) as u32;
    let lacunarity = decode(3, u[3]);
    let gain = decode(4, u[4]);
    let warp_amp = decode(5, u[5]);
    let warp_period = decode(6, u[6]);
    let redistribution = decode(7, u[7]);
    let detail_amp = decode(8, u[8]);
    let detail_gain = decode(9, u[9]);
    let detail_octaves = decode(10, u[10]) as u32;
    let nugget_amp = decode(11, u[11]);
    let aniso_ratio = decode(12, u[12]);
    let intensity = decode(13, u[13]);
    let deposition = decode(14, u[14]);
    let hardness_contrast = decode(15, u[15]);
    let diffusion = decode(16, u[16]);
    let ridged_mix = decode(17, u[17]);
    let relief_patchiness = decode(18, u[18]);

    // aniso_angle is a per-seed nuisance (the anisotropy metric is rotation-
    // invariant, so calibration fixed it at 0): give each course its own ridge
    // direction so the world grain isn't globally aligned. Half-turn period.
    let aniso_angle = rng.range_f64(0.0, core::f64::consts::PI);

    let erosion = ErosionParams {
        intensity,
        deposition,
        diffusion,
        hardness_contrast,
    };

    // 3. Lowland lake-field shrink (water mechanism, see LOWLAND_PERIOD_SHRINK):
    //    tighten lowland wavelengths into hole-scale closed basins. Keyed on a
    //    provisional (pre-shrink) forward relief estimate.
    let relief0 = relief_estimate(amplitude, base_period0, gain, redistribution, intensity);
    let lowland_k =
        1.0 - math::smoothstep(math::ln(16.0), math::ln(30.0), math::ln(relief0.max(1.0)));
    let base_period = (base_period0 * (1.0 - LOWLAND_PERIOD_SHRINK * lowland_k))
        .clamp(PERIOD_CLAMP.0, PERIOD_CLAMP.1);

    // 4. Final forward relief estimate (with the shrunk period) → water + report.
    let relief = relief_estimate(amplitude, base_period, gain, redistribution, intensity);
    let m = ((relief - 18.0) / (110.0 - 18.0)).clamp(0.0, 1.0);

    SampledParams {
        seed,
        mode: relief_band(relief),
        relief_target: relief,
        skew_target: skew_for_redistribution(redistribution),
        params: TerrainParams {
            amplitude,
            base_period,
            octaves,
            lacunarity,
            gain,
            warp_amp,
            warp_period,
            redistribution,
            detail_amp,
            detail_gain,
            detail_octaves,
            nugget_amp,
            aniso_ratio,
            aniso_angle,
            // detail_patchiness exists in the generator but is not a θ knob:
            // the spot-check found no measurable metric response in rolling or
            // flat regimes (the organization gaps are macro-structural, closed
            // by ridged_mix/relief_patchiness). Kept dormant for manual use.
            detail_patchiness: 0.0,
            ridged_mix,
            relief_patchiness,
        },
        erosion,
        water: sample_water(seed, relief, m),
    }
}

/// Draw a unit-space θ from p(θ): weighted-resample a design point (inverse-CDF
/// over the baked weights), then add small unit-space Gaussian jitter for
/// continuity between the discrete members. Deterministic.
fn draw_theta_unit(rng: &mut DetRng) -> [f64; NP] {
    let x = rng.next_f64();
    let di = PTHETA_CDF.iter().position(|&c| x <= c).unwrap_or(NPTS - 1);
    let mut u = PTHETA_U[di];
    for uk in u.iter_mut() {
        *uk = (*uk + PTHETA_JITTER * normal(rng)).clamp(0.0, 1.0);
    }
    u
}

/// Decode a unit value to real units per `PSPEC[k]` — the exact inverse map the
/// calibration used (`param_schema._from_unit`): log knobs `lo·(hi/lo)^u`,
/// linear `lo + u·(hi−lo)`, integer knobs rounded. libm `pow` keeps it
/// bit-identical cross-platform.
fn decode(k: usize, u: f64) -> f64 {
    let (lo, hi, is_log, is_int) = PSPEC[k];
    let u = u.clamp(0.0, 1.0);
    let v = if is_log {
        lo * math::pow(hi / lo, u)
    } else {
        lo + u * (hi - lo)
    };
    if is_int {
        v.round()
    } else {
        v
    }
}

/// Forward p2–p98 relief estimate (m) from the drawn knobs, via the calibrated
/// K-tables — the product the v8 sampler *inverted* to solve amplitude. Used
/// forward here, to feed the water sampler + the descriptive `relief_target`.
fn relief_estimate(
    amplitude: f64,
    base_period: f64,
    gain: f64,
    redistribution: f64,
    intensity: f64,
) -> f64 {
    (amplitude
        * k_relief(base_period, gain)
        * k_redist(redistribution)
        * k_erode(intensity, base_period))
    .max(0.0)
}

/// Relief-band label from the forward relief estimate (reporting only; the bands
/// overlap continuously, so this is a descriptor, not a hard class).
fn relief_band(relief: f64) -> ReliefMode {
    if relief < 20.0 {
        ReliefMode::Lowland
    } else if relief < 65.0 {
        ReliefMode::Rolling
    } else {
        ReliefMode::Mountain
    }
}

/// Water axes, fit to the atlas water masks (`xtask atlas-water`):
/// - Coverage medians saturate: ~8.1% lowland falling to ~2.2% for rolling
///   AND mountain (relief correlation is mostly "lowland is much wetter"),
///   with a wide residual (σ_ln ≈ 0.9 — Doral 16.6 vs Olympia 1.7).
/// - Dry-course probability rises with relief: 0% lowland / 8% rolling /
///   25% mountain in the atlas.
/// - A mountain lake-course tail (Jasper 11.5%): one dominant lake.
/// - Stream share of water is small on average (~20%) but occasionally
///   dominant (Colonial 88%, Banff 97%) — drawn with a heavy right tail,
///   relief-independent (the atlas signal is weak).
fn sample_water(seed: u64, relief: f64, m: f64) -> WaterParams {
    let mut rng = DetRng::new(seed, b"water-sampler-v1");
    let ln_r = math::ln(relief);

    // Fixed draw order: dry, lake-tail, coverage z, channel z, runoff, share,
    // river gate + size (all drawn unconditionally so branches never shift
    // the stream).
    let u_dry = rng.next_f64();
    let u_lake = rng.next_f64();
    let z_cov = normal(&mut rng);
    let z_chan = normal(&mut rng);
    let z_runoff = normal(&mut rng);
    let z_share = normal(&mut rng);
    let u_river = rng.next_f64();
    let z_river = normal(&mut rng);

    // Terrain water is LARGE features only (rivers, wide streams, lakes,
    // sizable ponds) — the strategic small ponds arrive with the holes in
    // the build phase. Lowland is the deliberate exception: hole-scale lake
    // fields covering ~20% ± 10% of the course (the basin-heavy noise floor
    // is set up in `sample_params`); rolling/mountain stay sparse.
    let lowland_k = 1.0 - math::smoothstep(math::ln(16.0), math::ln(30.0), ln_r);
    let p_dry = sigmoid(-2.44 + 1.46 * (ln_r - math::ln(38.0)));
    let p_lake = 0.14 * math::smoothstep(40.0, 80.0, relief);

    // Median coverage %: ~20% deep lowland blending down to ~2.2% by rolling;
    // the spread tightens on lowland so draws land in the 12–27% band the
    // terrain's basin capacity (~21%, `xtask lake-capacity`) can realize.
    let c_base = 3.2 + (2.2 - 3.2) * math::smoothstep(math::ln(13.0), math::ln(38.0), ln_r);
    let c_med = math::exp(
        math::ln(c_base) + (math::ln(LOWLAND_COV_MED) - math::ln(c_base)) * lowland_k,
    );
    let sigma = 0.9 - 0.62 * lowland_k;
    let (c_lo, c_hi) = (0.3 + 11.7 * lowland_k, 12.0 + 15.0 * lowland_k);
    let mut coverage_pct = math::exp(math::ln(c_med) + sigma * z_cov).clamp(c_lo, c_hi);
    // No terrain wetlands: all standing-water budget goes to lakes/ponds.
    let _ = z_share;
    let mut pond_share = 1.0;
    let mut lake_course = false;

    if u_lake < p_lake {
        // Jasper/Banff pattern: big water, one dominant lake.
        coverage_pct = 9.0 + 6.0 * rng.next_f64();
        pond_share = 1.0;
        lake_course = true;
    } else if u_dry < p_dry {
        coverage_pct = 0.0;
    }

    // Through-river courses: an external upstream catchment enters at the
    // world edge — the only way a 2 km world gets a genuinely wide river.
    // Two tiers: ~1% of wet courses get a MAJOR river (50–90 m, a full
    // crossing that splits the property), ~17% a regular one (14–45 m).
    let mut river_area = 0.0;
    if coverage_pct > 0.0 && !lake_course {
        if u_river < 0.01 {
            river_area = math::exp(math::ln(1.8e8) + 0.5 * z_river).clamp(1.0e8, 3.5e8);
            coverage_pct = coverage_pct.max(5.5);
        } else if u_river < 0.18 {
            river_area = math::exp(math::ln(2.0e7) + 0.8 * z_river).clamp(8.0e6, 8.0e7);
            coverage_pct = coverage_pct.max(4.0);
        }
    }

    // Wetter draws get denser channel networks (ρ ≈ 0.4 with the coverage
    // residual); the rest is independent spread. This is the PERENNIAL
    // initiation threshold — only collected mains carry visible water; the
    // fine network below it stays as dry swales (HAND reference).
    let z_a = -0.4 * z_cov + 0.9165 * z_chan;
    let stream_area_min = math::exp(math::ln(8.0e5) + 0.6 * z_a).clamp(2.0e5, 5.0e6);
    let runoff = math::exp(0.35 * z_runoff).clamp(0.5, 2.2);
    // No terrain wetlands (they return, if at all, as build-phase features).
    let wetland_share_cap = 0.0;
    let _ = m;

    // Large features only: every kept stream reads as a proper river
    // (≥ 10 m), and standing water must be a sizable pond/lake — mountains
    // demand the most (one or two real lakes).
    let min_stream_width = 10.0;
    // Floor ≈ the smallest deliberate lake (200 m × 25 m ellipse ≈ 4,000 m²).
    let min_body_area = 4000.0 + 4000.0 * math::smoothstep(45.0, 85.0, relief);

    WaterParams {
        coverage: coverage_pct / 100.0,
        stream_area_min,
        runoff,
        pond_share,
        wetland_share_cap,
        lake_course,
        river_area,
        min_stream_width,
        min_body_area,
        noise_seed: crate::mix_seed(seed, 6),
    }
}

fn sigmoid(x: f64) -> f64 {
    1.0 / (1.0 + math::exp(-x))
}

/// The octave rule (shared with calibration): enough layers to resolve
/// ~MIN_FEATURE_M under lacunarity 2, clamped to a sane band.
pub fn octaves_for(base_period: f64) -> u32 {
    let ratio = (base_period / MIN_FEATURE_M).max(2.0);
    let oct = (math::ln(ratio) / math::ln(2.0)).ceil() as i64 + 1;
    oct.clamp(3, 7) as u32
}

/// Calibration-consistent warp defaults for a bare (period, gain) pair.
/// `xtask calibrate` uses exactly this so the K table matches the sampler.
pub fn calibration_warp(base_period: f64) -> (f64, f64) {
    (0.10 * base_period, 1.15 * base_period)
}

/// Approximate standard normal via Irwin–Hall (sum of 12 uniforms − 6):
/// zero mean, unit sd, support ±6 — pure arithmetic, fully deterministic.
fn normal(rng: &mut DetRng) -> f64 {
    let mut s = 0.0;
    for _ in 0..12 {
        s += rng.next_f64();
    }
    s - 6.0
}

// ---- table interpolation -------------------------------------------------

fn axis_frac(axis: &[f64], v: f64) -> (usize, f64) {
    let v = v.clamp(axis[0], axis[axis.len() - 1]);
    for i in 0..axis.len() - 1 {
        if v <= axis[i + 1] {
            return (i, (v - axis[i]) / (axis[i + 1] - axis[i]));
        }
    }
    (axis.len() - 2, 1.0)
}

fn k_relief(period: f64, gain: f64) -> f64 {
    bilerp_table(&K_RELIEF, period, gain).max(0.05)
}

/// Redistribution strength for an exponent: `e = max(p, 1/p)` — the tables
/// are measured on the e ≥ 1 branch, the p < 1 side mirrors exactly.
fn redist_strength(p: f64) -> f64 {
    if p >= 1.0 {
        p
    } else {
        1.0 / p.max(1e-6)
    }
}

/// Relief multiplier of the redistribution exponent (1.0 at p = 1).
fn k_redist(p: f64) -> f64 {
    let (i, f) = axis_frac(&CAL_REDIST, redist_strength(p));
    (K_REDIST[i] + (K_REDIST[i + 1] - K_REDIST[i]) * f).max(0.05)
}

/// Forward height-skew estimate for a redistribution exponent (reporting only):
/// interpolate the calibrated skew(strength) curve. `p ≥ 1` (basins) gives
/// positive skew; `p < 1` (mirrored plateaus) gives the negated value.
fn skew_for_redistribution(p: f64) -> f64 {
    let (i, f) = axis_frac(&CAL_REDIST, redist_strength(p));
    let mag = SKEW_REDIST[i] + (SKEW_REDIST[i + 1] - SKEW_REDIST[i]) * f;
    if p >= 1.0 {
        mag
    } else {
        -mag
    }
}

fn bilerp_table(table: &[[f64; 5]; 7], period: f64, gain: f64) -> f64 {
    let (pi, pf) = axis_frac(&CAL_PERIODS, period);
    let (gi, gf) = axis_frac(&CAL_GAINS, gain);
    let a = table[pi][gi] + (table[pi][gi + 1] - table[pi][gi]) * gf;
    let b = table[pi + 1][gi] + (table[pi + 1][gi + 1] - table[pi + 1][gi]) * gf;
    a + (b - a) * pf
}

/// Pipeline relief multiplier of the erosion pass (measured by calibrate).
fn k_erode(intensity: f64, base_period: f64) -> f64 {
    let (ti, tf) = axis_frac(&CAL_ERODE_T, intensity);
    let (pi, pf) = axis_frac(&CAL_ERODE_P, base_period);
    let a = K_ERODE[ti][pi] + (K_ERODE[ti][pi + 1] - K_ERODE[ti][pi]) * pf;
    let b = K_ERODE[ti + 1][pi] + (K_ERODE[ti + 1][pi + 1] - K_ERODE[ti + 1][pi]) * pf;
    (a + (b - a) * tf).max(0.1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sampling_is_deterministic() {
        for seed in [0u64, 1, 42, u64::MAX] {
            let a = sample_params(seed);
            let b = sample_params(seed);
            assert_eq!(a.params, b.params);
            assert_eq!(a.relief_target, b.relief_target);
            assert_eq!(a.erosion, b.erosion);
        }
    }

    #[test]
    fn params_are_generation_safe() {
        // Every decode stays inside its PSPEC range (jitter clips in unit
        // space), so the whole draw is finite and generation-safe.
        for seed in 0..3000u64 {
            let s = sample_params(seed);
            let p = s.params;
            assert!(p.amplitude.is_finite() && (5.0..=200.0).contains(&p.amplitude));
            assert!((PERIOD_CLAMP.0..=PERIOD_CLAMP.1).contains(&p.base_period));
            assert!((3..=7).contains(&p.octaves));
            assert!((1.8..=2.3).contains(&p.lacunarity));
            assert!((0.35..=0.75).contains(&p.gain));
            assert!((0.0..=240.0).contains(&p.warp_amp));
            assert!((300.0..=2200.0).contains(&p.warp_period));
            assert!((0.25..=4.0).contains(&p.redistribution));
            // detail band
            assert!((0.1..=4.0).contains(&p.detail_amp));
            assert!((0.4..=0.72).contains(&p.detail_gain));
            assert!((2..=5).contains(&p.detail_octaves));
            assert!((0.0..=0.35).contains(&p.nugget_amp));
            // anisotropy
            assert!((1.0..=4.0).contains(&p.aniso_ratio));
            assert!((0.0..core::f64::consts::PI).contains(&p.aniso_angle));
            // landform organization (v10)
            assert!((-0.8..=0.8).contains(&p.ridged_mix));
            assert!((0.0..=0.8).contains(&p.relief_patchiness));
            assert_eq!(p.detail_patchiness, 0.0);
            // erosion (all from p(θ))
            let e = s.erosion;
            assert!((0.3..=6.5).contains(&e.intensity));
            assert!((0.1..=3.5).contains(&e.deposition));
            assert!((0.2..=3.0).contains(&e.diffusion));
            assert!((0.0..=0.8).contains(&e.hardness_contrast));
            assert!(s.relief_target.is_finite() && s.relief_target >= 0.0);
        }
    }

    #[test]
    fn ptheta_spans_atlas_diversity() {
        // The re-fit must reproduce the atlas's spread AND actually exercise the
        // new mechanisms (detail roughness, anisotropy, reactivated hardness) —
        // otherwise the coverage gains don't ship.
        let (mut relief_min, mut relief_max) = (f64::INFINITY, 0.0f64);
        let (mut basins, mut plateaus) = (0u32, 0u32);
        let (mut anisotropic, mut rough, mut hard) = (0u32, 0u32, 0u32);
        let (mut ridged, mut patchy) = (0u32, 0u32);
        let n = 4000u64;
        for seed in 0..n {
            let s = sample_params(seed);
            relief_min = relief_min.min(s.relief_target);
            relief_max = relief_max.max(s.relief_target);
            if s.params.redistribution > 1.15 {
                basins += 1;
            }
            if s.params.redistribution < 0.9 {
                plateaus += 1;
            }
            if s.params.aniso_ratio > 1.5 {
                anisotropic += 1;
            }
            if s.params.detail_amp > 0.5 {
                rough += 1;
            }
            if s.erosion.hardness_contrast > 0.2 {
                hard += 1;
            }
            if s.params.ridged_mix.abs() > 0.2 {
                ridged += 1;
            }
            if s.params.relief_patchiness > 0.2 {
                patchy += 1;
            }
        }
        // Relief spans lowland → rolling/mountain.
        assert!(relief_min < 15.0, "no lowland draws: min relief {relief_min}");
        assert!(relief_max > 50.0, "no high-relief draws: max relief {relief_max}");
        // Both distribution archetypes reachable (basin-and-hills / plateau).
        assert!(basins > 100, "basins rare: {basins}");
        assert!(plateaus > 100, "plateaus rare: {plateaus}");
        // The mechanisms are genuinely sampled.
        assert!(anisotropic > 100, "anisotropy not exercised: {anisotropic}");
        assert!(rough > 100, "detail roughness not exercised: {rough}");
        assert!(hard > 50, "hardness not reactivated: {hard}");
        // v10 landform-organization knobs are genuinely sampled.
        assert!(ridged > 100, "ridged_mix not exercised: {ridged}");
        assert!(patchy > 100, "relief_patchiness not exercised: {patchy}");
    }
}
